openapi: 3.0.3
info:
  description: Thornado REST API.
  title: Thornado API
  version: 0.1.0
servers:
- url: /
paths:
  /auth/accounts/{address}:
    get:
      parameters:
      - explode: false
        in: path
        name: address
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Account response
      summary: Account
  /thornado/node/{address}:
    get:
      parameters:
      - explode: false
        in: path
        name: address
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Node response
      summary: Node by address
  /thornado/nodes:
    get:
      responses:
        "200":
          description: Nodes response
      summary: Nodes
  /thornado/node/metrics:
    get:
      responses:
        "200":
          description: Node metrics response
      summary: Node metrics
  /thornado/node/slot/{slot}:
    get:
      parameters:
      - explode: false
        in: path
        name: slot
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          description: Node slot response
      summary: Node slot
  /thornado/config:
    get:
      responses:
        "200":
          description: Config response
      summary: Config values
  /thornado/config/nodes_all:
    get:
      responses:
        "200":
          description: All node config response
      summary: All node config values
  /thornado/config/nodes:
    get:
      responses:
        "200":
          description: Node config response
      summary: Node config values
  /thornado/config/node/{address}:
    get:
      parameters:
      - explode: false
        in: path
        name: address
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Node config response
      summary: Config values for node
  /thornado/version:
    get:
      responses:
        "200":
          description: Version response
      summary: Version
  /thornado/invariant/{path}:
    get:
      parameters:
      - explode: false
        in: path
        name: path
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Invariant response
      summary: Invariant
  /thornado/invariants:
    get:
      responses:
        "200":
          description: Invariants response
      summary: Invariants
  /thornado/balance/module/{name}:
    get:
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Module balance response
      summary: Module balance
  /thornado/config/defaults:
    get:
      responses:
        "200":
          description: Config defaults response
      summary: Config defaults
  /thornado/lastblock:
    get:
      responses:
        "200":
          description: Last block response
      summary: Last observed blocks
  /thornado/network_fee:
    get:
      responses:
        "200":
          description: Network fee response
      summary: BTC network fee
  /thornado/vault/{pub_key}:
    get:
      parameters:
      - explode: false
        in: path
        name: pub_key
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Vault response
      summary: Vault
  /thornado/vaults/base:
    get:
      responses:
        "200":
          description: Base vault response
      summary: Base vaults
  /thornado/vaults/pubkeys:
    get:
      responses:
        "200":
          description: Vault pubkeys response
      summary: Vault pubkeys
  /thornado/vaults/solvency:
    get:
      responses:
        "200":
          description: Vault solvency response
      summary: Vault solvency
  /thornado/tx/{tx_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: tx_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Transaction response
      summary: Transaction
  /thornado/txout:
    get:
      responses:
        "200":
          description: TxOut queue response
      summary: TxOut queue
  /thornado/txout/out:
    get:
      responses:
        "200":
          description: Outbound TxOut response
      summary: Outbound TxOut queue
  /thornado/txout/internal:
    get:
      responses:
        "200":
          description: Internal TxOut response
      summary: Internal TxOut queue
  /thornado/txout/all:
    get:
      responses:
        "200":
          description: All TxOut response
      summary: All TxOut queue
  /thornado/deposit/{deposit_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: deposit_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Deposit response
      summary: Deposit
  /thornado/shielder/redeem/{withdrawal_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: withdrawal_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Redeem response
      summary: Shielder redeem
  /thornado/shielder/nullifier/{nullifier_hash}:
    get:
      parameters:
      - explode: false
        in: path
        name: nullifier_hash
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Nullifier response
      summary: Shielder nullifier
  /thornado/shielder/sync:
    get:
      responses:
        "200":
          description: Shielder sync response
      summary: Shielder sync
  /thornado/shielder/redeem/quote/{amount_sats}:
    get:
      parameters:
      - explode: false
        in: path
        name: amount_sats
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          description: Redeem quote response
      summary: Shielder redeem quote
  /thornado/fees:
    get:
      responses:
        "200":
          description: Fee pool response
      summary: Fee pool
  /thornado/deposit/session/{owner}:
    get:
      parameters:
      - explode: false
        in: path
        name: owner
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Session response
      summary: Deposit session
  /thornado/bond/{node_pub_key}:
    get:
      parameters:
      - explode: false
        in: path
        name: node_pub_key
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Bond response
      summary: Node bond
  /thornado/node/auction/{auction_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: auction_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Auction response
      summary: Node slot auction
  /thornado/node/auctions:
    get:
      responses:
        "200":
          description: Auctions response
      summary: Node slot auctions
  /thornado/node/bid/{bid_id}:
    get:
      parameters:
      - explode: false
        in: path
        name: bid_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Bid response
      summary: Node slot bid
  /thornado/node/auction/{auction_id}/bids:
    get:
      parameters:
      - explode: false
        in: path
        name: auction_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Auction bids response
      summary: Node slot auction bids
  /thornado/deposit/address/{address}:
    get:
      parameters:
      - explode: false
        in: path
        name: address
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Deposit address response
      summary: Deposit address mapping
  /thornado/fee/entitlement/{node_pub_key}:
    get:
      parameters:
      - explode: false
        in: path
        name: node_pub_key
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Fee entitlement response
      summary: Node fee entitlement
  /thornado/fee/entitlements:
    get:
      responses:
        "200":
          description: Fee entitlements response
      summary: Node fee entitlements
  /thornado/block:
    get:
      responses:
        "200":
          description: Block response
      summary: Block
  /thornado/metric/keygen/{pub_key}:
    get:
      parameters:
      - explode: false
        in: path
        name: pub_key
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: FROST keygen metric response
      summary: FROST keygen metric by vault pubkey
  /thornado/metrics:
    get:
      responses:
        "200":
          description: FROST metrics response
      summary: FROST keygen and keysign metrics
  /thornado/keysign/{height}:
    get:
      parameters:
      - explode: false
        in: path
        name: height
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          description: Keysign response
      summary: TxOut keysign items
  /thornado/keysign/{height}/{pub_key}:
    get:
      parameters:
      - explode: false
        in: path
        name: height
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: false
        in: path
        name: pub_key
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Keysign response
      summary: TxOut keysign items by vault pubkey
  /thornado/keygen/{height}/{pub_key}:
    get:
      parameters:
      - explode: false
        in: path
        name: height
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: false
        in: path
        name: pub_key
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Keygen response
      summary: Keygen block by vault pubkey
  /thornado/upgrade_proposals:
    get:
      responses:
        "200":
          description: Upgrade proposals response
      summary: Upgrade proposals
  /thornado/upgrade_proposal/{name}:
    get:
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Upgrade proposal response
      summary: Upgrade proposal
  /thornado/upgrade_votes/{name}:
    get:
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Upgrade votes response
      summary: Upgrade votes
components:
  schemas: {}
