// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/type_reference_memo.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "gitlab.com/thorchain/thornode/v3/common"
	gitlab_com_thorchain_thornode_v3_common "gitlab.com/thorchain/thornode/v3/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReferenceMemo struct {
	Asset            gitlab_com_thorchain_thornode_v3_common.Asset  `protobuf:"bytes,1,opt,name=asset,proto3,customtype=gitlab.com/thorchain/thornode/v3/common.Asset" json:"asset"`
	Memo             string                                         `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Reference        string                                         `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Height           int64                                          `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	RegistrationHash gitlab_com_thorchain_thornode_v3_common.TxID   `protobuf:"bytes,5,opt,name=registration_hash,json=registrationHash,proto3,casttype=gitlab.com/thorchain/thornode/v3/common.TxID" json:"registration_hash,omitempty"`
	RegisteredBy     github_com_cosmos_cosmos_sdk_types.AccAddress  `protobuf:"bytes,6,opt,name=registered_by,json=registeredBy,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"registered_by,omitempty"`
	UsedByTxs        []gitlab_com_thorchain_thornode_v3_common.TxID `protobuf:"bytes,7,rep,name=used_by_txs,json=usedByTxs,proto3,casttype=gitlab.com/thorchain/thornode/v3/common.TxID" json:"used_by_txs,omitempty"`
}

func (m *ReferenceMemo) Reset()         { *m = ReferenceMemo{} }
func (m *ReferenceMemo) String() string { return proto.CompactTextString(m) }
func (*ReferenceMemo) ProtoMessage()    {}
func (*ReferenceMemo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eea4bdc8e6ddc83, []int{0}
}
func (m *ReferenceMemo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReferenceMemo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReferenceMemo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReferenceMemo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceMemo.Merge(m, src)
}
func (m *ReferenceMemo) XXX_Size() int {
	return m.Size()
}
func (m *ReferenceMemo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceMemo.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceMemo proto.InternalMessageInfo

func (m *ReferenceMemo) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *ReferenceMemo) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *ReferenceMemo) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ReferenceMemo) GetRegistrationHash() gitlab_com_thorchain_thornode_v3_common.TxID {
	if m != nil {
		return m.RegistrationHash
	}
	return ""
}

func (m *ReferenceMemo) GetRegisteredBy() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.RegisteredBy
	}
	return nil
}

func (m *ReferenceMemo) GetUsedByTxs() []gitlab_com_thorchain_thornode_v3_common.TxID {
	if m != nil {
		return m.UsedByTxs
	}
	return nil
}

func init() {
	proto.RegisterType((*ReferenceMemo)(nil), "types.ReferenceMemo")
}

func init() { proto.RegisterFile("types/type_reference_memo.proto", fileDescriptor_1eea4bdc8e6ddc83) }

var fileDescriptor_1eea4bdc8e6ddc83 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x6a, 0xe2, 0x40,
	0x18, 0xc7, 0x33, 0x1b, 0x75, 0x71, 0x54, 0xd8, 0x9d, 0x5d, 0x96, 0x20, 0x4b, 0x12, 0xf6, 0x94,
	0xc3, 0x6a, 0x76, 0x95, 0x3e, 0x80, 0xa1, 0x87, 0x16, 0x5a, 0x28, 0x41, 0x7a, 0x10, 0x4a, 0x88,
	0xc9, 0x34, 0x13, 0xda, 0x64, 0x64, 0x66, 0x2c, 0xc9, 0x5b, 0xf4, 0x89, 0x7a, 0xf6, 0xe8, 0xb1,
	0xf4, 0x20, 0x45, 0xdf, 0xc2, 0x53, 0x99, 0x89, 0xad, 0xde, 0x5a, 0x7a, 0xc9, 0xf7, 0xcf, 0xff,
	0x9b, 0xef, 0xc7, 0xff, 0x63, 0x06, 0x5a, 0xa2, 0x9c, 0x61, 0xee, 0xca, 0x6f, 0xc0, 0xf0, 0x35,
	0x66, 0x38, 0x8f, 0x70, 0x90, 0xe1, 0x8c, 0xf6, 0x67, 0x8c, 0x0a, 0x8a, 0xea, 0xea, 0x40, 0xf7,
	0x47, 0x44, 0xb3, 0x8c, 0xe6, 0x6e, 0x55, 0xaa, 0x5e, 0xf7, 0x67, 0x42, 0x13, 0xaa, 0xa4, 0x2b,
	0x55, 0xe5, 0xfe, 0x79, 0xd0, 0x61, 0xc7, 0x7f, 0x45, 0x9d, 0xe3, 0x8c, 0xa2, 0x09, 0xac, 0x87,
	0x9c, 0x63, 0x61, 0x00, 0x1b, 0x38, 0xad, 0x41, 0xa7, 0xbf, 0xa3, 0x8c, 0xa4, 0xe9, 0x1d, 0x2d,
	0x56, 0x96, 0xf6, 0xb4, 0xb2, 0x7a, 0x49, 0x2a, 0x6e, 0xc3, 0xa9, 0x6c, 0xba, 0x82, 0x50, 0x16,
	0x91, 0x30, 0xcd, 0x95, 0xca, 0x69, 0x8c, 0xdd, 0xbb, 0xa1, 0x7b, 0x38, 0xe6, 0x57, 0x48, 0x84,
	0x60, 0x4d, 0xa6, 0x35, 0xbe, 0xd8, 0xc0, 0x69, 0xfa, 0x4a, 0xa3, 0xdf, 0xb0, 0xf9, 0xb6, 0x8b,
	0xa1, 0xab, 0xc6, 0xde, 0x40, 0xbf, 0x60, 0x83, 0xe0, 0x34, 0x21, 0xc2, 0xa8, 0xd9, 0xc0, 0xd1,
	0xfd, 0xdd, 0x1f, 0xba, 0x82, 0xdf, 0x19, 0x4e, 0x52, 0x2e, 0x58, 0x28, 0x52, 0x9a, 0x07, 0x24,
	0xe4, 0xc4, 0xa8, 0xcb, 0x69, 0xef, 0xdf, 0x76, 0x65, 0xfd, 0xfd, 0x68, 0xbc, 0x71, 0x71, 0x7a,
	0xec, 0x7f, 0x3b, 0x44, 0x9d, 0x84, 0x9c, 0xa0, 0x4b, 0xd8, 0xa9, 0x3c, 0xcc, 0x70, 0x1c, 0x4c,
	0x4b, 0xa3, 0x61, 0x03, 0xa7, 0xed, 0xfd, 0xdf, 0x56, 0x9b, 0x93, 0x79, 0x85, 0x8e, 0x28, 0xcf,
	0x28, 0xdf, 0x95, 0x1e, 0x8f, 0x6f, 0xd4, 0xdd, 0xf0, 0xfe, 0x28, 0x8a, 0x46, 0x71, 0xcc, 0x30,
	0xe7, 0x7e, 0x7b, 0xcf, 0xf1, 0x4a, 0x74, 0x01, 0x5b, 0x73, 0xae, 0x88, 0x81, 0x28, 0xb8, 0xf1,
	0xd5, 0xd6, 0x3f, 0x15, 0xb8, 0x29, 0x21, 0x5e, 0x39, 0x2e, 0xb8, 0x77, 0xb6, 0x58, 0x9b, 0x60,
	0xb9, 0x36, 0xc1, 0xf3, 0xda, 0x04, 0xf7, 0x1b, 0x53, 0x5b, 0x6e, 0x4c, 0xed, 0x71, 0x63, 0x6a,
	0x93, 0xc1, 0xbb, 0xc8, 0xe2, 0xd0, 0x97, 0xc1, 0xa7, 0x0d, 0xf5, 0x2a, 0x86, 0x2f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x86, 0x32, 0xf8, 0xab, 0x6a, 0x02, 0x00, 0x00,
}

func (m *ReferenceMemo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReferenceMemo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReferenceMemo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UsedByTxs) > 0 {
		for iNdEx := len(m.UsedByTxs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.UsedByTxs[iNdEx])
			copy(dAtA[i:], m.UsedByTxs[iNdEx])
			i = encodeVarintTypeReferenceMemo(dAtA, i, uint64(len(m.UsedByTxs[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.RegisteredBy) > 0 {
		i -= len(m.RegisteredBy)
		copy(dAtA[i:], m.RegisteredBy)
		i = encodeVarintTypeReferenceMemo(dAtA, i, uint64(len(m.RegisteredBy)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RegistrationHash) > 0 {
		i -= len(m.RegistrationHash)
		copy(dAtA[i:], m.RegistrationHash)
		i = encodeVarintTypeReferenceMemo(dAtA, i, uint64(len(m.RegistrationHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Height != 0 {
		i = encodeVarintTypeReferenceMemo(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Reference) > 0 {
		i -= len(m.Reference)
		copy(dAtA[i:], m.Reference)
		i = encodeVarintTypeReferenceMemo(dAtA, i, uint64(len(m.Reference)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTypeReferenceMemo(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Asset.Size()
		i -= size
		if _, err := m.Asset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeReferenceMemo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypeReferenceMemo(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeReferenceMemo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReferenceMemo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Asset.Size()
	n += 1 + l + sovTypeReferenceMemo(uint64(l))
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTypeReferenceMemo(uint64(l))
	}
	l = len(m.Reference)
	if l > 0 {
		n += 1 + l + sovTypeReferenceMemo(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTypeReferenceMemo(uint64(m.Height))
	}
	l = len(m.RegistrationHash)
	if l > 0 {
		n += 1 + l + sovTypeReferenceMemo(uint64(l))
	}
	l = len(m.RegisteredBy)
	if l > 0 {
		n += 1 + l + sovTypeReferenceMemo(uint64(l))
	}
	if len(m.UsedByTxs) > 0 {
		for _, s := range m.UsedByTxs {
			l = len(s)
			n += 1 + l + sovTypeReferenceMemo(uint64(l))
		}
	}
	return n
}

func sovTypeReferenceMemo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeReferenceMemo(x uint64) (n int) {
	return sovTypeReferenceMemo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReferenceMemo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeReferenceMemo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReferenceMemo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReferenceMemo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reference", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reference = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrationHash = gitlab_com_thorchain_thornode_v3_common.TxID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredBy", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegisteredBy = append(m.RegisteredBy[:0], dAtA[iNdEx:postIndex]...)
			if m.RegisteredBy == nil {
				m.RegisteredBy = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedByTxs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UsedByTxs = append(m.UsedByTxs, gitlab_com_thorchain_thornode_v3_common.TxID(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeReferenceMemo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeReferenceMemo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeReferenceMemo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeReferenceMemo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeReferenceMemo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeReferenceMemo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeReferenceMemo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeReferenceMemo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeReferenceMemo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeReferenceMemo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeReferenceMemo = fmt.Errorf("proto: unexpected end of group")
)
