[workspace]
members = [
    "crates/thornado-shielder",
    "crates/thornado-ffi",
    "crates/thornado-web-wasm",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
axum = "0.7"
bitcoin = { version = "0.32", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
frost-core = "3"
frost-secp256k1 = "3"
frost-secp256k1-tr = "2.2"
frost-rerandomized = "3"
hex = "0.4"
http = "1"
incrementalmerkletree = "0.8"
nonempty = "0.11"
orchard = "0.13.1"
rand_core = { version = "0.6", features = ["getrandom"] }
rand_chacha = "0.3"
redb = "2"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shardtree = "0.6"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
tower = "0.5"
wasm-bindgen = "0.2"
zcash_note_encryption = "0.4"
