package thorchain

import (
	"github.com/thornadocash/go-thornado/common"
	"github.com/thornadocash/go-thornado/x/thorchain/types"
)

const (
	ModuleName             = types.ModuleName
	ReserveName            = types.ReserveName
	AsgardName             = types.AsgardName
	BondName               = types.BondName
	LendingName            = types.LendingName
	AffiliateCollectorName = types.AffiliateCollectorName
	TreasuryName           = types.TreasuryName
	RouterKey              = types.RouterKey
	StoreKey               = types.StoreKey
	DefaultCodespace       = types.DefaultCodespace

	// Vaults
	AsgardVault   = types.VaultType_AsgardVault
	UnknownVault  = types.VaultType_UnknownVault
	ActiveVault   = types.VaultStatus_ActiveVault
	InactiveVault = types.VaultStatus_InactiveVault
	RetiringVault = types.VaultStatus_RetiringVault
	InitVault     = types.VaultStatus_InitVault

	// Node status
	NodeActive      = types.NodeStatus_Active
	NodeWhiteListed = types.NodeStatus_Whitelisted
	NodeDisabled    = types.NodeStatus_Disabled
	NodeSelected    = types.NodeStatus_Selected
	NodeStandby     = types.NodeStatus_Standby
	NodeUnknown     = types.NodeStatus_Unknown

	// Node type
	NodeTypeUnknown   = types.NodeType_TypeUnknown
	NodeTypeValidator = types.NodeType_TypeValidator
	NodeTypeVault     = types.NodeType_TypeVault

	// Bond type
	BondPaid     = types.BondType_bond_paid
	BondReturned = types.BondType_bond_returned
	BondCost     = types.BondType_bond_cost
	BondReward   = types.BondType_bond_reward
	AsgardKeygen = types.KeygenType_AsgardKeygen

	// Swap Type
	MarketSwap = types.SwapType_market
	LimitSwap  = types.SwapType_limit

	// Advanced Swap Queue Mode
	AdvSwapQueueModeDisabled   = types.AdvSwapQueueModeDisabled
	AdvSwapQueueModeEnabled    = types.AdvSwapQueueModeEnabled
	AdvSwapQueueModeMarketOnly = types.AdvSwapQueueModeMarketOnly

	// Mint/Burn type
	MintSupplyType = types.MintBurnSupplyType_mint
	BurnSupplyType = types.MintBurnSupplyType_burn
)

var (
	NewNetwork                      = types.NewNetwork
	NewProtocolOwnedLiquidity       = types.NewProtocolOwnedLiquidity
	NewPOLReserveDeposit            = types.NewPOLReserveDeposit
	NewObservedTx                   = common.NewObservedTx
	NewTssVoter                     = types.NewTssVoter
	NewBanVoter                     = types.NewBanVoter
	NewErrataTxVoter                = types.NewErrataTxVoter
	NewObservedTxVoter              = types.NewObservedTxVoter
	NewMsgTradeAccountDeposit       = types.NewMsgTradeAccountDeposit
	NewMsgTradeAccountWithdrawal    = types.NewMsgTradeAccountWithdrawal
	NewMsgSecuredAssetDeposit       = types.NewMsgSecuredAssetDeposit
	NewMsgSecuredAssetWithdraw      = types.NewMsgSecuredAssetWithdraw
	NewMsgMimir                     = types.NewMsgMimir
	NewMsgNodePauseChain            = types.NewMsgNodePauseChain
	NewMsgDeposit                   = types.NewMsgDeposit
	NewMsgTssPool                   = types.NewMsgTssPool
	NewMsgTssPoolV2                 = types.NewMsgTssPoolV2
	NewMsgTssKeysignFail            = types.NewMsgTssKeysignFail
	NewMsgObservedTxIn              = types.NewMsgObservedTxIn
	NewMsgObservedTxOut             = types.NewMsgObservedTxOut
	NewMsgNoOp                      = types.NewMsgNoOp
	NewMsgConsolidate               = types.NewMsgConsolidate
	NewMsgDonate                    = types.NewMsgDonate
	NewMsgSwap                      = types.NewMsgSwap
	NewMsgModifyLimitSwap           = types.NewMsgModifyLimitSwap
	NewKeygen                       = types.NewKeygen
	NewKeygenBlock                  = types.NewKeygenBlock
	NewMsgSetNodeKeys               = types.NewMsgSetNodeKeys
	NewMsgReferenceMemo             = types.NewMsgReferenceMemo
	NewMsgSwitch                    = types.NewMsgSwitch
	NewMsgOperatorRotate            = types.NewMsgOperatorRotate
	NewMsgPriceFeedQuorumBatch      = types.NewMsgPriceFeedQuorumBatch
	NewTxOut                        = types.NewTxOut
	NewEventRewards                 = types.NewEventRewards
	NewEventPOLReserveDeploy        = types.NewEventPOLReserveDeploy
	NewEventPool                    = types.NewEventPool
	NewEventDonate                  = types.NewEventDonate
	NewEventSwap                    = types.NewEventSwap
	NewEventAffiliateFee            = types.NewEventAffiliateFee
	NewEventStreamingSwap           = types.NewEventStreamingSwap
	NewEventLimitSwap               = types.NewEventLimitSwap
	NewEventModifyLimitSwap         = types.NewEventModifyLimitSwap
	NewEventLimitSwapClose          = types.NewEventLimitSwapClose
	NewEventRefund                  = types.NewEventRefund
	NewEventBond                    = types.NewEventBond
	NewEventReBond                  = types.NewEventReBond
	NewEventGas                     = types.NewEventGas
	NewEventScheduledOutbound       = types.NewEventScheduledOutbound
	NewEventSecurity                = types.NewEventSecurity
	NewEventSlash                   = types.NewEventSlash
	NewEventSlashPoint              = types.NewEventSlashPoint
	NewEventReserve                 = types.NewEventReserve
	NewEventErrata                  = types.NewEventErrata
	NewEventFee                     = types.NewEventFee
	NewEventOutbound                = types.NewEventOutbound
	NewEventSetMimir                = types.NewEventSetMimir
	NewEventSetNodeMimir            = types.NewEventSetNodeMimir
	NewEventTssKeygenSuccess        = types.NewEventTssKeygenSuccess
	NewEventTssKeygenFailure        = types.NewEventTssKeygenFailure
	NewEventTssKeygenMetric         = types.NewEventTssKeygenMetric
	NewEventTssKeysignMetric        = types.NewEventTssKeysignMetric
	NewEventPoolBalanceChanged      = types.NewEventPoolBalanceChanged
	NewEventMintBurn                = types.NewEventMintBurn
	NewEventVersion                 = types.NewEventVersion
	NewEventSecuredAssetWithdraw    = types.NewEventSecuredAssetWithdraw
	NewEventSwitch                  = types.NewEventSwitch
	NewEventOperatorRotate          = types.NewEventOperatorRotate
	NewEventOraclePrice             = types.NewEventOraclePrice
	NewEventFailedOutboundRecovery  = types.NewEventFailedOutboundRecovery
	NewPoolMod                      = types.NewPoolMod
	NewMsgRefundTx                  = types.NewMsgRefundTx
	NewMsgOutboundTx                = types.NewMsgOutboundTx
	NewMsgMigrate                   = types.NewMsgMigrate
	NewMsgRagnarok                  = types.NewMsgRagnarok
	ModuleCdc                       = types.ModuleCdc
	RegisterLegacyAminoCodec        = types.RegisterLegacyAminoCodec
	RegisterInterfaces              = types.RegisterInterfaces
	NewBondProviders                = types.NewBondProviders
	NewBondProvider                 = types.NewBondProvider
	NewNodeAccount                  = types.NewNodeAccount
	NewVault                        = types.NewVault
	NewVaultV2                      = types.NewVaultV2
	NewReserveContributor           = types.NewReserveContributor
	NewMsgReserveContributor        = types.NewMsgReserveContributor
	NewMsgBond                      = types.NewMsgBond
	NewMsgUnBond                    = types.NewMsgUnBond
	NewMsgReBond                    = types.NewMsgReBond
	NewMsgErrataTx                  = types.NewMsgErrataTx
	NewMsgBan                       = types.NewMsgBan
	NewMsgLeave                     = types.NewMsgLeave
	NewMsgSetVersion                = types.NewMsgSetVersion
	NewMsgProposeUpgrade            = types.NewMsgProposeUpgrade
	NewMsgApproveUpgrade            = types.NewMsgApproveUpgrade
	NewMsgRejectUpgrade             = types.NewMsgRejectUpgrade
	NewMsgSetIPAddress              = types.NewMsgSetIPAddress
	NewMsgNetworkFee                = types.NewMsgNetworkFee
	NewNetworkFee                   = types.NewNetworkFee
	NewReferenceMemo                = types.NewReferenceMemo
	NewStreamingSwap                = types.NewStreamingSwap
	GetRandomVault                  = types.GetRandomVault
	GetRandomTx                     = types.GetRandomTx
	GetRandomObservedTx             = types.GetRandomObservedTx
	GetRandomTxOutItem              = types.GetRandomTxOutItem
	GetRandomObservedTxVoter        = types.GetRandomObservedTxVoter
	GetRandomValidatorNode          = types.GetRandomValidatorNode
	GetRandomVaultNode              = types.GetRandomVaultNode
	GetRandomTHORAddress            = types.GetRandomTHORAddress
	GetRandomRUNEAddress            = types.GetRandomRUNEAddress
	GetRandomETHAddress             = types.GetRandomETHAddress
	GetRandomGAIAAddress            = types.GetRandomGAIAAddress
	GetRandomBTCAddress             = types.GetRandomBTCAddress
	GetRandomLTCAddress             = types.GetRandomLTCAddress
	GetRandomDOGEAddress            = types.GetRandomDOGEAddress
	GetRandomBCHAddress             = types.GetRandomBCHAddress
	GetRandomTxHash                 = types.GetRandomTxHash
	GetRandomBech32Addr             = types.GetRandomBech32Addr
	GetRandomBech32ConsensusPubKey  = types.GetRandomBech32ConsensusPubKey
	GetRandomPubKey                 = types.GetRandomPubKey
	GetRandomPubKeySet              = types.GetRandomPubKeySet
	GetCurrentVersion               = types.GetCurrentVersion
	SetupConfigForTest              = types.SetupConfigForTest
	HasSimpleMajority               = types.HasSimpleMajority
	HasSuperMajority                = types.HasSuperMajority
	HasMinority                     = types.HasMinority
	DefaultGenesis                  = types.DefaultGenesis
	NewSolvencyVoter                = types.NewSolvencyVoter
	NewMsgSolvency                  = types.NewMsgSolvency
	NewSwapperClout                 = types.NewSwapperClout
	NewMsgShielderRegisterPow       = types.NewMsgShielderRegisterPow
	NewMsgShielderSettleDeposit     = types.NewMsgShielderSettleDeposit
	NewMsgShielderPostCommitments   = types.NewMsgShielderPostCommitments
	NewMsgShielderRequestWithdrawal = types.NewMsgShielderRequestWithdrawal
	NewMsgShielderSettleFees        = types.NewMsgShielderSettleFees
	NewMsgShielderSplitFees         = types.NewMsgShielderSplitFees
	NewMsgNodeSlotAuctionCreate     = types.NewMsgNodeSlotAuctionCreate
	NewMsgNodeSlotAuctionBidPow     = types.NewMsgNodeSlotAuctionBidPow
	NewMsgNodeSlotAuctionSelectBid  = types.NewMsgNodeSlotAuctionSelectBid
	NewMsgNodeSlotAuctionSplit      = types.NewMsgNodeSlotAuctionSplit
)

type (
	// Msgs
	MsgSend                      = types.MsgSend
	MsgDeposit                   = types.MsgDeposit
	MsgBond                      = types.MsgBond
	MsgUnBond                    = types.MsgUnBond
	MsgReBond                    = types.MsgReBond
	MsgNoOp                      = types.MsgNoOp
	MsgTradeAccountDeposit       = types.MsgTradeAccountDeposit
	MsgTradeAccountWithdrawal    = types.MsgTradeAccountWithdrawal
	MsgSecuredAssetDeposit       = types.MsgSecuredAssetDeposit
	MsgSecuredAssetWithdraw      = types.MsgSecuredAssetWithdraw
	MsgConsolidate               = types.MsgConsolidate
	MsgDonate                    = types.MsgDonate
	MsgOutboundTx                = types.MsgOutboundTx
	MsgMimir                     = types.MsgMimir
	MsgNodePauseChain            = types.MsgNodePauseChain
	MsgMigrate                   = types.MsgMigrate
	MsgRagnarok                  = types.MsgRagnarok
	MsgRefundTx                  = types.MsgRefundTx
	MsgErrataTx                  = types.MsgErrataTx
	MsgBan                       = types.MsgBan
	MsgSwap                      = types.MsgSwap
	MsgModifyLimitSwap           = types.MsgModifyLimitSwap
	MsgSetVersion                = types.MsgSetVersion
	MsgProposeUpgrade            = types.MsgProposeUpgrade
	MsgApproveUpgrade            = types.MsgApproveUpgrade
	MsgRejectUpgrade             = types.MsgRejectUpgrade
	MsgSetIPAddress              = types.MsgSetIPAddress
	MsgSetNodeKeys               = types.MsgSetNodeKeys
	MsgLeave                     = types.MsgLeave
	MsgMaint                     = types.MsgMaint
	MsgReserveContributor        = types.MsgReserveContributor
	MsgObservedTxIn              = types.MsgObservedTxIn
	MsgObservedTxOut             = types.MsgObservedTxOut
	MsgTssPool                   = types.MsgTssPool
	MsgTssKeysignFail            = types.MsgTssKeysignFail
	MsgNetworkFee                = types.MsgNetworkFee
	MsgReferenceMemo             = types.MsgReferenceMemo
	MsgSolvency                  = types.MsgSolvency
	MsgSwitch                    = types.MsgSwitch
	MsgOperatorRotate            = types.MsgOperatorRotate
	MsgShielderRegisterPow       = types.MsgShielderRegisterPow
	MsgShielderSettleDeposit     = types.MsgShielderSettleDeposit
	MsgShielderPostCommitments   = types.MsgShielderPostCommitments
	MsgShielderRequestWithdrawal = types.MsgShielderRequestWithdrawal
	MsgShielderSettleFees        = types.MsgShielderSettleFees
	MsgNodeSlotAuctionCreate     = types.MsgNodeSlotAuctionCreate
	MsgNodeSlotAuctionBidPow     = types.MsgNodeSlotAuctionBidPow
	MsgNodeSlotAuctionSelectBid  = types.MsgNodeSlotAuctionSelectBid
	MsgNodeSlotAuctionSplit      = types.MsgNodeSlotAuctionSplit

	// Keeper structs
	StreamingSwap            = types.StreamingSwap
	StreamingSwaps           = types.StreamingSwaps
	ObservedTxs              = common.ObservedTxs
	ObservedTx               = common.ObservedTx
	ObservedTxVoter          = types.ObservedTxVoter
	ObservedTxVoters         = types.ObservedTxVoters
	BanVoter                 = types.BanVoter
	ErrataTxVoter            = types.ErrataTxVoter
	TssVoter                 = types.TssVoter
	TssKeysignFailVoter      = types.TssKeysignFailVoter
	TxOutItem                = types.TxOutItem
	TxOut                    = types.TxOut
	Keygen                   = types.Keygen
	KeygenBlock              = types.KeygenBlock
	EventSwap                = types.EventSwap
	EventAffiliateFee        = types.EventAffiliateFee
	EventDonate              = types.EventDonate
	EventRewards             = types.EventRewards
	EventErrata              = types.EventErrata
	EventReserve             = types.EventReserve
	PoolAmt                  = types.PoolAmt
	PoolMod                  = types.PoolMod
	PoolMods                 = types.PoolMods
	ReserveContributor       = types.ReserveContributor
	ReserveContributors      = types.ReserveContributors
	Vault                    = types.Vault
	Vaults                   = types.Vaults
	NodeAccount              = types.NodeAccount
	NodeAccounts             = types.NodeAccounts
	NodeStatus               = types.NodeStatus
	BondProviders            = types.BondProviders
	BondProvider             = types.BondProvider
	Network                  = types.Network
	ProtocolOwnedLiquidity   = types.ProtocolOwnedLiquidity
	POLReserveDeposit        = types.POLReserveDeposit
	VaultStatus              = types.VaultStatus
	GasPool                  = types.GasPool
	EventGas                 = types.EventGas
	EventPool                = types.EventPool
	EventRefund              = types.EventRefund
	EventBond                = types.EventBond
	EventFee                 = types.EventFee
	EventSlash               = types.EventSlash
	EventOutbound            = types.EventOutbound
	NetworkFee               = types.NetworkFee
	PriceFeed                = types.PriceFeed
	OraclePrice              = types.OraclePrice
	ObservedNetworkFeeVoter  = types.ObservedNetworkFeeVoter
	Jail                     = types.Jail
	RagnarokWithdrawPosition = types.RagnarokWithdrawPosition
	ChainContract            = types.ChainContract
	Blame                    = types.Blame
	Node                     = types.Node
	ReferenceMemo            = types.ReferenceMemo
	AffiliateFeeCollector    = types.AffiliateFeeCollector
	NodeMimir                = types.NodeMimir
	NodeMimirs               = types.NodeMimirs
	SwapperClout             = types.SwapperClout
	TradeAccount             = types.TradeAccount
	TradeUnit                = types.TradeUnit
	SecuredAsset             = types.SecuredAsset
	VolumeBucket             = types.VolumeBucket
	ContractInfo             = types.ContractInfo
	ShielderSession          = types.ShielderSession
	ShielderDeposit          = types.ShielderDeposit
	ShielderWithdrawal       = types.ShielderWithdrawal
	NodeSlotAuction          = types.NodeSlotAuction
	NodeSlotBid              = types.NodeSlotBid

	// Proto
	ProtoStrings = types.ProtoStrings
	ProtoInt64   = types.ProtoInt64
)
