[package]
name = "thornado-shielder"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = []
proof-tests = ["dep:ark-circom"]

[dependencies]
ark-bn254 = "0.5"
ark-circom = { version = "0.6", optional = true, default-features = false, features = ["ethereum"] }
ark-ec = "0.5"
ark-ff = "0.5"
ark-groth16 = "0.5"
ark-serialize = "0.5"
ark-snark = "0.5"
hex.workspace = true
blake-hash = "0.3"
digest = "0.10"
digest08 = { package = "digest", version = "0.8" }
hmac = "0.12"
k256 = { version = "0.13", features = ["arithmetic", "ecdsa", "sha256"] }
num-bigint = { version = "0.4", features = ["std"] }
num-traits = "0.2"
sha3 = "0.10"
rand_chacha.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
