[package]
name = "thornado-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = ["orchard-zcash"]
orchard-zcash = [
    "dep:incrementalmerkletree",
    "dep:nonempty",
    "dep:orchard",
    "dep:shardtree",
    "dep:zcash_note_encryption",
]

[dependencies]
ark-bn254.workspace = true
ark-ff.workspace = true
ark-groth16.workspace = true
ark-relations.workspace = true
ark-serialize.workspace = true
bitcoin.workspace = true
frost-core.workspace = true
frost-secp256k1.workspace = true
frost-rerandomized.workspace = true
hex.workspace = true
incrementalmerkletree = { workspace = true, optional = true }
nonempty = { workspace = true, optional = true }
orchard = { workspace = true, optional = true }
rand_chacha.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
shardtree = { workspace = true, optional = true }
sha2.workspace = true
thiserror.workspace = true
tiny-keccak.workspace = true
zcash_note_encryption = { workspace = true, optional = true }

[dev-dependencies]
tempfile = "3"
