openapi: 3.0.3
info:
  title: Thornado API
  description: Thornado REST API.
  version: 0.1.0
paths:
  /thornado/ping:
    get:
      summary: Ping
      responses:
        "200":
          description: Pong
  /thornado/account/{address}:
    get:
      summary: Account
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Account response
  /thornado/balances/{address}:
    get:
      summary: Balances
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Balances response
  /thornado/inbound_addresses:
    get:
      summary: Inbound addresses
      responses:
        "200":
          description: Inbound address response
  /thornado/vaults/pubkeys:
    get:
      summary: Vault pubkeys
      responses:
        "200":
          description: Vault pubkeys response
  /thornado/vault/{pub_key}:
    get:
      summary: Vault
      parameters:
        - name: pub_key
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Vault response
  /thornado/tx/{hash}:
    get:
      summary: Transaction
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Transaction response
  /thornado/tx/status/{hash}:
    get:
      summary: Transaction status
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Transaction status response
  /thornado/tx/stages/{hash}:
    get:
      summary: Transaction stages
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Transaction stages response
  /thornado/reference_memo/{reference}:
    get:
      summary: Reference memo
      parameters:
        - name: reference
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Reference memo response
  /thornado/reference_memo/hash/{hash}:
    get:
      summary: Reference memo by hash
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Reference memo response
  /thornado/reference_memo/preflight:
    get:
      summary: Reference memo preflight
      responses:
        "200":
          description: Reference memo preflight response
  /thornado/mimir:
    get:
      summary: Mimir values
      responses:
        "200":
          description: Mimir response
  /thornado/constants:
    get:
      summary: Constants
      responses:
        "200":
          description: Constants response
  /thornado/version:
    get:
      summary: Version
      responses:
        "200":
          description: Version response
  /thornado/block:
    get:
      summary: Latest block
      responses:
        "200":
          description: Block response
  /thornado/block/{height}:
    get:
      summary: Block by height
      parameters:
        - name: height
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Block response
  /thornado/lastblock:
    get:
      summary: Last observed blocks
      responses:
        "200":
          description: Last block response
  /thornado/tss/keygen:
    get:
      summary: TSS keygen metrics
      responses:
        "200":
          description: TSS keygen response
  /thornado/tss/keysign:
    get:
      summary: TSS keysign metrics
      responses:
        "200":
          description: TSS keysign response
  /thornado/contract:
    get:
      summary: Contract infos
      responses:
        "200":
          description: Contract infos response
  /thornado/contract/{address}:
    get:
      summary: Contract info
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Contract info response
