syntax = "proto3";
package types;

option go_package = "github.com/thornadocash/go-thornado/x/thornado/types";

import "google/api/annotations.proto";
import "gogoproto/gogo.proto";
import "types/query_account.proto";
import "types/query_balance_module.proto";
import "types/query_block.proto";
import "types/query_constant_values.proto";
import "types/query_deposit.proto";
import "types/query_export.proto";
import "types/query_invariants.proto";
import "types/query_keystore.proto";
import "types/query_last_block.proto";
import "types/query_network_fee.proto";
import "types/query_fee.proto";
import "types/query_config.proto";
import "types/query_node.proto";
import "types/query_shielder.proto";
import "types/query_tss.proto";
import "types/query_tx.proto";
import "types/query_upgrade.proto";
import "types/query_vault.proto";
import "types/query_version.proto";
import "types/type_network_fee.proto";
import "types/type_tss_metric.proto";

option (gogoproto.marshaler_all) = true;

service Query {
  rpc Account(QueryAccountRequest) returns (QueryAccountResponse) {
    option (google.api.http).get = "/auth/accounts/{address}";
  }

  rpc Export(QueryExportRequest) returns (QueryExportResponse) {
    option (google.api.http).get = "/thornado/export";
  }

  rpc Node(QueryNodeRequest) returns (QueryNodeResponse) {
    option (google.api.http).get = "/thornado/node/{address}";
  }

  rpc Nodes(QueryNodesRequest) returns (QueryNodesResponse) {
    option (google.api.http).get = "/thornado/nodes";
  }

  rpc NodeMetrics(QueryNodeMetricsRequest) returns (QueryNodeMetricsResponse) {
    option (google.api.http).get = "/thornado/node/metrics";
  }

  rpc NodeSlot(QueryNodeSlotRequest) returns (QueryNodeSlotResponse) {
    option (google.api.http).get = "/thornado/node/slot/{slot}";
  }

  rpc ConfigValues(QueryConfigValuesRequest) returns (QueryConfigValuesResponse) {
    option (google.api.http).get = "/thornado/config";
  }

  rpc ConfigNodesAllValues(QueryConfigNodesAllValuesRequest) returns (QueryConfigNodesAllValuesResponse) {
    option (google.api.http).get = "/thornado/config/nodes_all";
  }

  rpc ConfigNodesValues(QueryConfigNodesValuesRequest) returns (QueryConfigNodesValuesResponse) {
    option (google.api.http).get = "/thornado/config/nodes";
  }

  rpc ConfigNodeValues(QueryConfigNodeValuesRequest) returns (QueryConfigNodeValuesResponse) {
    option (google.api.http).get = "/thornado/config/node/{address}";
  }

  rpc Version(QueryVersionRequest) returns (QueryVersionResponse) {
    option (google.api.http).get = "/thornado/version";
  }

  rpc Invariant(QueryInvariantRequest) returns (QueryInvariantResponse) {
    option (google.api.http).get = "/thornado/invariant/{path}";
  }

  rpc Invariants(QueryInvariantsRequest) returns (QueryInvariantsResponse) {
    option (google.api.http).get = "/thornado/invariants";
  }

  rpc BalanceModule(QueryBalanceModuleRequest) returns (QueryBalanceModuleResponse) {
    option (google.api.http).get = "/thornado/balance/module/{name}";
  }

  rpc ConfigDefaults(QueryConfigDefaultsRequest) returns (QueryConfigDefaultsResponse) {
    option (google.api.http).get = "/thornado/config/defaults";
  }

  rpc LastBlocks(QueryLastBlocksRequest) returns (QueryLastBlocksResponse) {
    option (google.api.http).get = "/thornado/lastblock";
  }

  rpc NetworkFeeCurrent(QueryNetworkFeeRequest) returns (NetworkFee) {
    option (google.api.http).get = "/thornado/network_fee";
  }

  rpc Vault(QueryVaultRequest) returns (QueryVaultResponse) {
    option (google.api.http).get = "/thornado/vault/{pub_key}";
  }

  rpc BaseVaults(QueryBaseVaultsRequest) returns (QueryBaseVaultsResponse) {
    option (google.api.http).get = "/thornado/vaults/base";
  }

  rpc VaultsPubkeys(QueryVaultsPubkeysRequest) returns (QueryVaultsPubkeysResponse) {
    option (google.api.http).get = "/thornado/vaults/pubkeys";
  }

  rpc VaultSolvency(QueryVaultSolvencyRequest) returns (QueryVaultSolvencyResponse) {
    option (google.api.http).get = "/thornado/vaults/solvency";
  }

  rpc Tx(QueryTxRequest) returns (QueryTxResponse) {
    option (google.api.http).get = "/thornado/tx/{tx_id}";
  }

  rpc TxOut(QueryTxOutRequest) returns (QueryTxOutResponse) {
    option (google.api.http).get = "/thornado/txout";
  }

  rpc TxOutOut(QueryTxOutRequest) returns (QueryTxOutResponse) {
    option (google.api.http).get = "/thornado/txout/out";
  }

  rpc TxOutInternal(QueryTxOutRequest) returns (QueryTxOutResponse) {
    option (google.api.http).get = "/thornado/txout/internal";
  }

  rpc TxOutAll(QueryTxOutRequest) returns (QueryTxOutResponse) {
    option (google.api.http).get = "/thornado/txout/all";
  }

  rpc Deposit(QueryDepositRequest) returns (QueryDepositResponse) {
    option (google.api.http).get = "/thornado/deposit/{deposit_id}";
  }

  rpc ShielderRedeem(QueryShielderRedeemRequest) returns (QueryShielderRedeemResponse) {
    option (google.api.http).get = "/thornado/shielder/redeem/{withdrawal_id}";
  }

  rpc ShielderNullifier(QueryShielderNullifierRequest) returns (QueryShielderNullifierResponse) {
    option (google.api.http).get = "/thornado/shielder/nullifier/{nullifier_hash}";
  }

  rpc ShielderSync(QueryShielderSyncRequest) returns (QueryShielderSyncResponse) {
    option (google.api.http).get = "/thornado/shielder/sync";
  }

  rpc ShielderRoots(QueryShielderRootsRequest) returns (QueryShielderRootsResponse) {
    option (google.api.http).get = "/thornado/shielder/roots";
  }

  rpc ShielderLeaves(QueryShielderLeavesRequest) returns (QueryShielderLeavesResponse) {
    option (google.api.http).get = "/thornado/shielder/leaves/{denomination_sats}";
  }

  rpc ShielderRedeemQuote(QueryShielderRedeemQuoteRequest) returns (QueryShielderRedeemQuoteResponse) {
    option (google.api.http).get = "/thornado/shielder/redeem/quote/{amount_sats}";
  }

  rpc FeePool(QueryFeePoolRequest) returns (QueryFeePoolResponse) {
    option (google.api.http).get = "/thornado/fees";
  }

  rpc DepositSession(QueryDepositSessionRequest) returns (QueryDepositSessionResponse) {
    option (google.api.http).get = "/thornado/deposit/session/{owner}";
  }

  rpc NodeBond(QueryNodeBondRequest) returns (QueryNodeBondResponse) {
    option (google.api.http).get = "/thornado/bond/{node_pub_key}";
  }

  rpc NodeSlotAuction(QueryNodeSlotAuctionRequest) returns (QueryNodeSlotAuctionResponse) {
    option (google.api.http).get = "/thornado/node/auction/{auction_id}";
  }

  rpc NodeSlotAuctions(QueryNodeSlotAuctionsRequest) returns (QueryNodeSlotAuctionsResponse) {
    option (google.api.http).get = "/thornado/node/auctions";
  }

  rpc NodeSlotBid(QueryNodeSlotBidRequest) returns (QueryNodeSlotBidResponse) {
    option (google.api.http).get = "/thornado/node/bid/{bid_id}";
  }

  rpc NodeSlotAuctionBids(QueryNodeSlotAuctionBidsRequest) returns (QueryNodeSlotAuctionBidsResponse) {
    option (google.api.http).get = "/thornado/node/auction/{auction_id}/bids";
  }

  rpc VaultDepositAddress(QueryVaultDepositAddressRequest) returns (QueryVaultDepositAddressResponse) {
    option (google.api.http).get = "/thornado/deposit/address/{address}";
  }

  rpc NodeFeeEntitlement(QueryNodeFeeEntitlementRequest) returns (QueryNodeFeeEntitlementResponse) {
    option (google.api.http).get = "/thornado/fee/entitlement/{node_pub_key}";
  }

  rpc NodeFeeEntitlements(QueryNodeFeeEntitlementsRequest) returns (QueryNodeFeeEntitlementsResponse) {
    option (google.api.http).get = "/thornado/fee/entitlements";
  }

  rpc Block(QueryBlockRequest) returns (QueryBlockResponse) {
    option (google.api.http).get = "/thornado/block";
  }

  rpc TssKeygenMetric(QueryTssKeygenMetricRequest) returns (QueryTssKeygenMetricResponse) {
    option (google.api.http).get = "/thornado/metric/keygen/{pub_key}";
  }

  rpc TssMetric(QueryTssMetricRequest) returns (QueryTssMetricResponse) {
    option (google.api.http).get = "/thornado/metrics";
  }

  rpc Keysign(QueryKeysignRequest) returns (QueryKeysignResponse) {
    option (google.api.http).get = "/thornado/keysign/{height}";
  }

  rpc KeysignPubkey(QueryKeysignPubkeyRequest) returns (QueryKeysignResponse) {
    option (google.api.http).get = "/thornado/keysign/{height}/{pub_key}";
  }

  rpc Keygen(QueryKeygenRequest) returns (QueryKeygenResponse) {
    option (google.api.http).get = "/thornado/keygen/{height}/{pub_key}";
  }

  rpc UpgradeProposals(QueryUpgradeProposalsRequest) returns (QueryUpgradeProposalsResponse) {
    option (google.api.http).get = "/thornado/upgrade_proposals";
  }

  rpc UpgradeProposal(QueryUpgradeProposalRequest) returns (QueryUpgradeProposalResponse) {
    option (google.api.http).get = "/thornado/upgrade_proposal/{name}";
  }

  rpc UpgradeVotes(QueryUpgradeVotesRequest) returns (QueryUpgradeVotesResponse) {
    option (google.api.http).get = "/thornado/upgrade_votes/{name}";
  }

}
