syntax = "proto3";
package types;

import "cosmos/msg/v1/msg.proto";
import "types/msg_deposit.proto";
import "types/msg_errata.proto";
import "types/msg_config.proto";
import "types/msg_network_fee.proto";
import "types/msg_node_pause_chain.proto";
import "types/msg_observed_txin.proto";
import "types/msg_observed_txout.proto";
import "types/msg_observed_tx_quorum.proto";
import "types/msg_operator_rotate.proto";
import "types/msg_send.proto";
import "types/msg_set_ip_address.proto";
import "types/msg_set_node_keys.proto";
import "types/msg_shielder.proto";
import "types/msg_solvency.proto";
import "types/msg_frost_keysign_fail.proto";
import "types/msg_keygen_vault.proto";
import "types/msg_version.proto";
import "types/msg_upgrade.proto";
import "types/msg_maint.proto";
import "types/msg_leave.proto";

option go_package = "github.com/thornadocash/go-thornado/x/thornado/types";

// Msg defines the bank Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  rpc Deposit(MsgDeposit) returns (MsgEmpty);
  rpc ErrataTx(MsgErrataTx) returns (MsgEmpty);
  rpc ErrataTxQuorum(MsgErrataTxQuorum) returns (MsgEmpty);
  rpc Config(MsgConfig) returns (MsgEmpty);
  rpc NetworkFee(MsgNetworkFee) returns (MsgEmpty);
  rpc NetworkFeeQuorum(MsgNetworkFeeQuorum) returns (MsgEmpty);
  rpc NodePauseChain(MsgNodePauseChain) returns (MsgEmpty);
  rpc OperatorRotate(MsgOperatorRotate) returns (MsgEmpty);
  rpc Maint(MsgMaint) returns (MsgEmpty);
  rpc Leave(MsgLeave) returns (MsgEmpty);
  rpc ObservedTxIn(MsgObservedTxIn) returns (MsgEmpty);
  rpc ObservedTxOut(MsgObservedTxOut) returns (MsgEmpty);
  rpc ObservedTxQuorum(MsgObservedTxQuorum) returns (MsgEmpty);
  rpc Send(MsgSend) returns (MsgEmpty);
  rpc SetIPAddress(MsgSetIPAddress) returns (MsgEmpty);
  rpc SetNodeKeys(MsgSetNodeKeys) returns (MsgEmpty);
  rpc Solvency(MsgSolvency) returns (MsgEmpty);
  rpc SolvencyQuorum(MsgSolvencyQuorum) returns (MsgEmpty);
  rpc FrostKeysignFail(MsgFrostKeysignFail) returns (MsgEmpty);
  rpc KeygenVault(MsgKeygenVault) returns (MsgEmpty);
  rpc SetVersion(MsgSetVersion) returns (MsgEmpty);
  rpc ProposeUpgrade(MsgProposeUpgrade) returns (MsgEmpty);
  rpc ApproveUpgrade(MsgApproveUpgrade) returns (MsgEmpty);
  rpc RejectUpgrade(MsgRejectUpgrade) returns (MsgEmpty);
  rpc DepositRequestPow(MsgDepositRequestPow) returns (MsgDepositRequestPowResponse);
  rpc ShielderShield(MsgShielderShield) returns (MsgShielderShieldResponse);
  rpc ShielderRedeem(MsgShielderRedeem) returns (MsgShielderRedeemResponse);
  rpc ShielderShieldFees(MsgShielderShieldFees) returns (MsgShielderShieldFeesResponse);
  rpc NodeOperatorFeeSet(MsgNodeOperatorFeeSet) returns (MsgEmpty);
  rpc NodeSlotAuctionCreate(MsgNodeSlotAuctionCreate) returns (MsgNodeSlotAuctionCreateResponse);
  rpc NodeSlotAuctionBidCreate(MsgNodeSlotAuctionBidCreate) returns (MsgNodeSlotAuctionBidCreateResponse);
  rpc NodeSlotAuctionSelectBid(MsgNodeSlotAuctionSelectBid) returns (MsgEmpty);
  rpc NodeSaleShield(MsgNodeSaleShield) returns (MsgShielderShieldResponse);
  rpc BondFromNotes(MsgBondFromNotes) returns (MsgBondFromNotesResponse);
}

// MsgEmpty is the return type for all current Msg Server messages
message MsgEmpty {}
