syntax = "proto3";
package types;

option go_package = "github.com/thornadocash/go-thornado/x/thornado/types";
option (gogoproto.goproto_stringer_all) = false;
option (gogoproto.stringer_all) = false;
option (gogoproto.goproto_getters_all) = false;

import "common/common.proto";
import "gogoproto/gogo.proto";

message TxOutInput {
  option (gogoproto.stringer) = true;

  string tx_id = 1
      [ (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID" ];
  uint32 vout = 2;
  uint64 amount_sats = 3;
  uint64 path_index = 4;
}

message TxOutItem {
  string chain = 1 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.Chain",
    (gogoproto.jsontag) = "chain"
  ];
  string to_address = 2 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.Address",
    (gogoproto.jsontag) = "to_address"
  ];
  string vault_pub_key = 3
      [ (gogoproto.casttype) =
            "github.com/thornadocash/go-thornado/common.PubKey" ];
  common.Coin coin = 4
      [ (gogoproto.nullable) = false, (gogoproto.jsontag) = "coin" ];
  repeated common.Coin max_gas = 6 [
    (gogoproto.castrepeated) = "github.com/thornadocash/go-thornado/common.Gas",
    (gogoproto.nullable) = false,
    (gogoproto.jsontag) = "max_gas"
  ];
  int64 gas_rate = 7;
  string in_hash = 8
      [ (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID" ];
  string out_hash = 9
      [ (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID" ];
  string module_name = 10 [ json_name = "-", (gogoproto.jsontag) = "-" ];
  string aggregator = 11;
  string aggregator_target_asset = 12;
  string aggregator_target_limit = 13 [
    (gogoproto.customtype) = "cosmossdk.io/math.Uint",
    (gogoproto.nullable) = true
  ];
  string vault_pub_key_eddsa = 15 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.PubKey",
    (gogoproto.nullable) = true
  ];
  uint64 vault_path_index = 17;
  string tx_type = 18;
  uint32 out_vout = 19;
  repeated TxOutInput source_inputs = 20 [ (gogoproto.nullable) = false ];
}

message TxOut {
  option (gogoproto.stringer) = true;
  int64 height = 1;
  repeated TxOutItem tx_array = 2 [ (gogoproto.nullable) = false ];
  uint64 epoch = 3;
  string status = 4;
  string signing_leader = 5 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.PubKey"
  ];
  uint64 signing_attempt = 6;
  int64 retry_until_height = 7;
}
