syntax = "proto3";
package types;

option go_package = "github.com/thornadocash/go-thornado/x/thornado/types";
option (gogoproto.goproto_stringer_all) = false;
option (gogoproto.stringer_all) = false;
option (gogoproto.goproto_getters_all) = false;

import "gogoproto/gogo.proto";

message ChainContract {
  string chain = 1 [ (gogoproto.casttype) =
                         "github.com/thornadocash/go-thornado/common.Chain" ];
  string router = 2 [ (gogoproto.casttype) =
                          "github.com/thornadocash/go-thornado/common.Address" ];
}
