syntax = "proto3";
package types;

option go_package = "github.com/thornadocash/go-thornado/x/thornado/types";

import "common/common.proto";
import "types/type_tx_out.proto";
import "gogoproto/gogo.proto";

enum BondType {
  bond_paid = 0;
  bond_returned = 1;
  reserved 2;
}

message EventBond {
  string amount = 1 [
    (gogoproto.customtype) = "cosmossdk.io/math.Uint",
    (gogoproto.nullable) = false
  ];
  BondType bond_type = 2;
  common.Tx tx_in = 3 [ (gogoproto.nullable) = false ];
  bytes node_address = 4
      [ (gogoproto.casttype) =
            "github.com/cosmos/cosmos-sdk/types.AccAddress" ];
  bytes bond_address = 5
      [ (gogoproto.casttype) =
            "github.com/cosmos/cosmos-sdk/types.AccAddress" ];
}

message GasPool {
  common.Asset asset = 1 [
    (gogoproto.nullable) = false,
    (gogoproto.customtype) = "github.com/thornadocash/go-thornado/common.Asset"
  ];
  string asset_amt = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.Uint",
    (gogoproto.nullable) = false
  ];
  int64 count = 4;
}

message EventGas {
  repeated GasPool pools = 1 [ (gogoproto.nullable) = false ];
}

message EventScheduledOutbound {
  TxOutItem out_tx = 1 [ (gogoproto.nullable) = false ];
}

message EventSecurity {
  string msg = 1;
  common.Tx tx = 2 [ (gogoproto.nullable) = false ];
}


message EventFee {
  string tx_id = 1 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID",
    (gogoproto.customname) = "TxID"
  ];
  common.Fee fee = 2 [ (gogoproto.nullable) = false ];
}

message EventOutbound {
  string in_tx_id = 1 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID",
    (gogoproto.customname) = "InTxID"
  ];
  common.Tx tx = 2 [ (gogoproto.nullable) = false ];
}

message EventFrostKeygenSuccess {
  string pub_key = 1 [ (gogoproto.casttype) =
                           "github.com/thornadocash/go-thornado/common.PubKey" ];
  repeated string members = 2;
  int64 height = 3;
}

message EventFrostKeygenFailure {
  string fail_reason = 1;
  bool is_unicast = 2;
  repeated string blame_nodes = 3;
  string round = 4;
  int64 height = 5;
}

message EventFrostKeygenMetric {
  string pub_key = 1 [ (gogoproto.casttype) =
                           "github.com/thornadocash/go-thornado/common.PubKey" ];
  int64 median_duration_ms = 2;
}

message EventFrostKeysignMetric {
  string tx_id = 1 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID",
    (gogoproto.customname) = "TxID"
  ];
  int64 median_duration_ms = 2;
}

message EventPenaltyPoint {
  bytes node_address = 1
      [ (gogoproto.casttype) =
            "github.com/cosmos/cosmos-sdk/types.AccAddress" ];
  int64 penalty_points = 2;
  string reason = 3;
}


enum MintBurnSupplyType {
  mint = 0;
  burn = 1;
}

message EventMintBurn {
  MintBurnSupplyType supply = 1;
  string denom = 2;
  string amount = 3 [
    (gogoproto.customtype) = "cosmossdk.io/math.Uint",
    (gogoproto.nullable) = false
  ];
  string reason = 4;
}



message EventSetConfig {
  string key = 1;
  string value = 2;
}

message EventSetNodeConfig {
  string key = 1;
  string value = 2;
  string address = 3;
}

message EventVersion { string version = 1; }

message EventOperatorRotate {
  bytes signer = 1
      [ (gogoproto.casttype) =
            "github.com/cosmos/cosmos-sdk/types.AccAddress" ];
  bytes node_address = 2
      [ (gogoproto.casttype) =
            "github.com/cosmos/cosmos-sdk/types.AccAddress" ];
  bytes operator_address = 3
      [ (gogoproto.casttype) =
            "github.com/cosmos/cosmos-sdk/types.AccAddress" ];
}

message EventOraclePrice {
  string symbol = 1;
  string price = 2;
}

message EventFailedOutboundRecovery {
  string in_tx_id = 1 [
    (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID",
    (gogoproto.customname) = "InTxID"
  ];
  common.Coin coin = 2 [ (gogoproto.nullable) = false ];
  string recovery_type = 3;
  string destination = 4
      [ (gogoproto.casttype) =
            "github.com/thornadocash/go-thornado/common.Address" ];
}
