// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgEmpty is the return type for all current Msg Server messages
type MsgEmpty struct {
}

func (m *MsgEmpty) Reset()         { *m = MsgEmpty{} }
func (m *MsgEmpty) String() string { return proto.CompactTextString(m) }
func (*MsgEmpty) ProtoMessage()    {}
func (*MsgEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_991dda0e66fd389c, []int{0}
}
func (m *MsgEmpty) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEmpty.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEmpty.Merge(m, src)
}
func (m *MsgEmpty) XXX_Size() int {
	return m.Size()
}
func (m *MsgEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEmpty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgEmpty)(nil), "types.MsgEmpty")
}

func init() { proto.RegisterFile("types/tx.proto", fileDescriptor_991dda0e66fd389c) }

var fileDescriptor_991dda0e66fd389c = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0xc7, 0x89, 0x5a, 0x28, 0x9a, 0xb6, 0x01, 0x46, 0x7c, 0xc9, 0x50, 0x17, 0xd1, 0x4a, 0x48,
	0xad, 0x88, 0xd5, 0xd2, 0xaa, 0xaa, 0xb8, 0xa8, 0x08, 0x25, 0x15, 0xa2, 0x90, 0x34, 0x06, 0x54,
	0x21, 0xad, 0x2c, 0xe3, 0x39, 0x38, 0x5e, 0x62, 0x8f, 0xf1, 0x8c, 0x43, 0x72, 0xb7, 0x8f, 0xb0,
	0x8f, 0xb1, 0x97, 0xfb, 0x18, 0x7b, 0xc9, 0xe5, 0x5e, 0xae, 0xe0, 0x62, 0x5f, 0x63, 0xe5, 0xaf,
	0x8c, 0xcd, 0x4c, 0x58, 0xae, 0xa2, 0x39, 0xbf, 0xf3, 0x3f, 0x73, 0x8e, 0xe7, 0x3f, 0xa3, 0xa0,
	0x3a, 0x1f, 0x85, 0xc0, 0x0c, 0x3e, 0x6c, 0x84, 0x11, 0xe5, 0x14, 0x4f, 0xa7, 0x6b, 0x6d, 0xc5,
	0xa1, 0xcc, 0xa7, 0xcc, 0xf0, 0x99, 0x6b, 0x0c, 0x7e, 0x49, 0x7e, 0x32, 0xae, 0xad, 0x64, 0xf9,
	0x3e, 0x73, 0x2d, 0x02, 0x21, 0x65, 0x1e, 0xcf, 0xc1, 0xb2, 0x00, 0x10, 0x45, 0x36, 0xb7, 0xe5,
	0xb8, 0x43, 0x83, 0x2b, 0xaf, 0x28, 0xb4, 0x26, 0xe2, 0x01, 0xf0, 0x5b, 0x1a, 0x5d, 0x5b, 0x57,
	0x00, 0x39, 0xdc, 0x28, 0x41, 0x4a, 0xc0, 0x0a, 0xed, 0x98, 0x81, 0xe5, 0xf4, 0x6c, 0x2f, 0xc8,
	0x33, 0xbe, 0x13, 0x19, 0xf4, 0x92, 0x41, 0x34, 0x00, 0x62, 0xf1, 0xe1, 0x18, 0xeb, 0x4a, 0x4c,
	0xe3, 0xa2, 0xdb, 0x4d, 0x25, 0xb7, 0x6e, 0x62, 0x1a, 0xc5, 0x7e, 0x9e, 0xa3, 0x89, 0x9c, 0x30,
	0xf2, 0x1c, 0x48, 0xfa, 0x23, 0x39, 0x5b, 0x14, 0x8c, 0x41, 0x40, 0xe4, 0x5d, 0x19, 0x70, 0xcb,
	0x0b, 0x2d, 0x9b, 0x90, 0x08, 0x18, 0x93, 0x9b, 0x4e, 0x78, 0x3a, 0xda, 0x35, 0x8c, 0x0a, 0xbc,
	0x5a, 0xc2, 0x3d, 0x0f, 0xfa, 0x04, 0x22, 0x05, 0xa1, 0xfd, 0x01, 0x04, 0xce, 0x48, 0xfe, 0x52,
	0x9c, 0xb1, 0xb4, 0x9a, 0xe7, 0x06, 0xd6, 0x95, 0xed, 0xf5, 0xf3, 0x8c, 0x75, 0x91, 0x71, 0x0d,
	0x23, 0x17, 0x02, 0x6b, 0x60, 0xc7, 0x7d, 0x2e, 0x9f, 0xe7, 0x00, 0x22, 0xe6, 0xd1, 0x40, 0x06,
	0x71, 0xe8, 0x46, 0x36, 0x29, 0xce, 0x66, 0x49, 0x00, 0xdf, 0xf6, 0x82, 0xbc, 0xd0, 0x26, 0x42,
	0xb3, 0xc7, 0xcc, 0x3d, 0xf0, 0x43, 0x3e, 0xfa, 0xf5, 0xcd, 0x1c, 0xfa, 0xe2, 0x98, 0xb9, 0x78,
	0x1b, 0x7d, 0xf5, 0x77, 0x66, 0x12, 0xbc, 0xd0, 0x48, 0x65, 0x8d, 0x63, 0xe6, 0xe6, 0x21, 0x6d,
	0x4e, 0x84, 0x52, 0x19, 0x36, 0xd0, 0xec, 0x41, 0x6a, 0x9d, 0xd3, 0x21, 0xc6, 0x25, 0x98, 0xc7,
	0x64, 0xc1, 0x2e, 0xaa, 0x17, 0xf0, 0xbf, 0xf4, 0xe4, 0xf0, 0xaa, 0x2c, 0xcb, 0x88, 0x2c, 0xfe,
	0x19, 0xcd, 0xec, 0xa7, 0x86, 0xc4, 0xf3, 0x02, 0x65, 0x11, 0x39, 0x79, 0x07, 0xa1, 0x93, 0xcc,
	0xa5, 0x2d, 0x00, 0xbc, 0x28, 0xb0, 0x88, 0xca, 0xa2, 0xbf, 0xd0, 0xbc, 0xc0, 0x79, 0x83, 0x9a,
	0x4a, 0x3a, 0xa9, 0xc5, 0x5d, 0x54, 0x3f, 0xa1, 0x04, 0x3a, 0x89, 0xfb, 0xf7, 0x13, 0xf3, 0x97,
	0xe7, 0xab, 0x12, 0x59, 0xfc, 0x07, 0xfa, 0xa6, 0x9d, 0x5b, 0xfb, 0x74, 0x78, 0x18, 0xe0, 0x65,
	0x91, 0x50, 0x8e, 0xcb, 0xc2, 0x3f, 0xd1, 0xb7, 0x22, 0xa1, 0x1d, 0x73, 0xbc, 0xa2, 0x52, 0xb6,
	0x63, 0xae, 0x9c, 0x58, 0x64, 0xc8, 0x13, 0x3f, 0x66, 0x72, 0x81, 0x2d, 0xf4, 0xa5, 0x09, 0x01,
	0xc1, 0x75, 0x01, 0x92, 0xb5, 0x72, 0x3a, 0x13, 0xf8, 0x61, 0x67, 0x2f, 0xbb, 0x60, 0xe5, 0xe9,
	0xca, 0x71, 0x59, 0xf8, 0x3b, 0xfa, 0xda, 0x04, 0x9e, 0x7c, 0xbc, 0x23, 0x18, 0x31, 0xbc, 0x54,
	0xd1, 0x15, 0x61, 0xa5, 0x37, 0xcd, 0xfc, 0xe6, 0x95, 0xbd, 0x59, 0xc4, 0x94, 0x67, 0x57, 0x40,
	0xd9, 0x9b, 0x55, 0xa2, 0x14, 0x9f, 0x32, 0x76, 0x94, 0x5d, 0xe6, 0x96, 0xed, 0xf5, 0xcb, 0xe2,
	0x2a, 0x51, 0x4e, 0x78, 0x94, 0x5e, 0xf4, 0xf3, 0xe4, 0x9e, 0x97, 0x27, 0x2c, 0x85, 0x95, 0x16,
	0x37, 0x81, 0x9f, 0x67, 0x8f, 0x40, 0xd9, 0xe2, 0x22, 0xaa, 0x6c, 0xb4, 0x13, 0xd1, 0x90, 0x32,
	0x38, 0xcb, 0x1e, 0x89, 0x72, 0xa3, 0x55, 0xa2, 0x14, 0xef, 0x85, 0x61, 0x44, 0x07, 0x2a, 0x71,
	0x95, 0x28, 0x5d, 0xda, 0x85, 0x97, 0xe0, 0xf0, 0x42, 0x5b, 0x72, 0x69, 0x05, 0xc8, 0xd2, 0x7f,
	0xd0, 0x62, 0x27, 0x79, 0xd0, 0x5b, 0x00, 0x24, 0x3b, 0x81, 0xa6, 0xcd, 0x9d, 0x1e, 0xd6, 0xcb,
	0xad, 0xcb, 0x5c, 0x2e, 0x74, 0x86, 0x16, 0xf2, 0xc7, 0xac, 0x0b, 0x37, 0x31, 0x30, 0xde, 0xa1,
	0xb7, 0x78, 0x4d, 0x7a, 0xe9, 0x04, 0xd4, 0x7e, 0x78, 0x02, 0x76, 0x81, 0x85, 0x34, 0x60, 0x80,
	0xff, 0x45, 0x75, 0x33, 0x7f, 0xff, 0xb3, 0xdf, 0x8a, 0x75, 0x2a, 0x44, 0xdb, 0x98, 0x44, 0x54,
	0xd5, 0xba, 0x40, 0x00, 0x7c, 0x55, 0xb5, 0x8c, 0xa8, 0xaa, 0x65, 0x64, 0x5c, 0xed, 0x7f, 0x84,
	0xab, 0xfb, 0xb4, 0x00, 0x18, 0x5e, 0x9f, 0xd4, 0x45, 0x42, 0xb5, 0x1f, 0x9f, 0xa2, 0xe3, 0xca,
	0x36, 0x5a, 0x4a, 0xae, 0x9f, 0xd9, 0xa7, 0x7c, 0x2f, 0x76, 0xb8, 0x47, 0x83, 0xfd, 0x08, 0x6c,
	0x0e, 0xf8, 0xfb, 0xea, 0x9b, 0x27, 0x25, 0x68, 0x5b, 0x9f, 0x49, 0x18, 0x6f, 0xf1, 0x42, 0xda,
	0xa2, 0xe9, 0x91, 0xe4, 0xcc, 0x26, 0x6f, 0x91, 0x25, 0x3c, 0xef, 0xdc, 0xda, 0x68, 0xf5, 0x91,
	0xda, 0x84, 0x3e, 0x38, 0xbc, 0xe9, 0x11, 0xbc, 0x39, 0x71, 0x87, 0x71, 0x8e, 0xec, 0xaf, 0x0b,
	0xa9, 0xdf, 0xdc, 0x0f, 0x93, 0xfb, 0x7d, 0xae, 0x2d, 0xb4, 0xe9, 0x57, 0x1f, 0xdf, 0xfe, 0x54,
	0x6b, 0x9e, 0xbc, 0xbb, 0xd7, 0x6b, 0x77, 0xf7, 0x7a, 0xed, 0xc3, 0xbd, 0x5e, 0x7b, 0xfd, 0xa0,
	0x4f, 0xdd, 0x3d, 0xe8, 0x53, 0xef, 0x1f, 0xf4, 0xa9, 0x8b, 0xdf, 0x5c, 0x8f, 0xf7, 0xe2, 0xcb,
	0x86, 0x43, 0x7d, 0x83, 0xf7, 0x68, 0x14, 0xd8, 0x84, 0x3a, 0x36, 0xeb, 0x19, 0x2e, 0xdd, 0x2e,
	0xd6, 0xc6, 0x70, 0x8c, 0x8c, 0x74, 0xc3, 0xcb, 0x99, 0xf4, 0xdf, 0xc0, 0xce, 0xa7, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x25, 0xbc, 0xa1, 0xbb, 0x58, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgEmpty, error)
	ErrataTx(ctx context.Context, in *MsgErrataTx, opts ...grpc.CallOption) (*MsgEmpty, error)
	ErrataTxQuorum(ctx context.Context, in *MsgErrataTxQuorum, opts ...grpc.CallOption) (*MsgEmpty, error)
	Config(ctx context.Context, in *MsgConfig, opts ...grpc.CallOption) (*MsgEmpty, error)
	NetworkFee(ctx context.Context, in *MsgNetworkFee, opts ...grpc.CallOption) (*MsgEmpty, error)
	NetworkFeeQuorum(ctx context.Context, in *MsgNetworkFeeQuorum, opts ...grpc.CallOption) (*MsgEmpty, error)
	NodePauseChain(ctx context.Context, in *MsgNodePauseChain, opts ...grpc.CallOption) (*MsgEmpty, error)
	ObservedTxIn(ctx context.Context, in *MsgObservedTxIn, opts ...grpc.CallOption) (*MsgEmpty, error)
	ObservedTxOut(ctx context.Context, in *MsgObservedTxOut, opts ...grpc.CallOption) (*MsgEmpty, error)
	ObservedTxQuorum(ctx context.Context, in *MsgObservedTxQuorum, opts ...grpc.CallOption) (*MsgEmpty, error)
	Send(ctx context.Context, in *MsgSend, opts ...grpc.CallOption) (*MsgEmpty, error)
	SetIPAddress(ctx context.Context, in *MsgSetIPAddress, opts ...grpc.CallOption) (*MsgEmpty, error)
	SetNodeKeys(ctx context.Context, in *MsgSetNodeKeys, opts ...grpc.CallOption) (*MsgEmpty, error)
	Solvency(ctx context.Context, in *MsgSolvency, opts ...grpc.CallOption) (*MsgEmpty, error)
	SolvencyQuorum(ctx context.Context, in *MsgSolvencyQuorum, opts ...grpc.CallOption) (*MsgEmpty, error)
	TssKeysignFail(ctx context.Context, in *MsgTssKeysignFail, opts ...grpc.CallOption) (*MsgEmpty, error)
	KeygenVault(ctx context.Context, in *MsgKeygenVault, opts ...grpc.CallOption) (*MsgEmpty, error)
	SetVersion(ctx context.Context, in *MsgSetVersion, opts ...grpc.CallOption) (*MsgEmpty, error)
	ProposeUpgrade(ctx context.Context, in *MsgProposeUpgrade, opts ...grpc.CallOption) (*MsgEmpty, error)
	ApproveUpgrade(ctx context.Context, in *MsgApproveUpgrade, opts ...grpc.CallOption) (*MsgEmpty, error)
	RejectUpgrade(ctx context.Context, in *MsgRejectUpgrade, opts ...grpc.CallOption) (*MsgEmpty, error)
	PriceFeedQuorumBatch(ctx context.Context, in *MsgPriceFeedQuorumBatch, opts ...grpc.CallOption) (*MsgEmpty, error)
	DepositRequestPow(ctx context.Context, in *MsgDepositRequestPow, opts ...grpc.CallOption) (*MsgDepositRequestPowResponse, error)
	ShielderShield(ctx context.Context, in *MsgShielderShield, opts ...grpc.CallOption) (*MsgShielderShieldResponse, error)
	ShielderRedeem(ctx context.Context, in *MsgShielderRedeem, opts ...grpc.CallOption) (*MsgShielderRedeemResponse, error)
	ShielderShieldFees(ctx context.Context, in *MsgShielderShieldFees, opts ...grpc.CallOption) (*MsgShielderShieldFeesResponse, error)
	NodeSlotAuctionCreate(ctx context.Context, in *MsgNodeSlotAuctionCreate, opts ...grpc.CallOption) (*MsgNodeSlotAuctionCreateResponse, error)
	NodeSlotAuctionBidPow(ctx context.Context, in *MsgNodeSlotAuctionBidPow, opts ...grpc.CallOption) (*MsgDepositRequestPowResponse, error)
	NodeSlotAuctionSelectBid(ctx context.Context, in *MsgNodeSlotAuctionSelectBid, opts ...grpc.CallOption) (*MsgEmpty, error)
	NodeSlotAuctionShield(ctx context.Context, in *MsgNodeSlotAuctionShield, opts ...grpc.CallOption) (*MsgShielderShieldResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ErrataTx(ctx context.Context, in *MsgErrataTx, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/ErrataTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ErrataTxQuorum(ctx context.Context, in *MsgErrataTxQuorum, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/ErrataTxQuorum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Config(ctx context.Context, in *MsgConfig, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) NetworkFee(ctx context.Context, in *MsgNetworkFee, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/NetworkFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) NetworkFeeQuorum(ctx context.Context, in *MsgNetworkFeeQuorum, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/NetworkFeeQuorum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) NodePauseChain(ctx context.Context, in *MsgNodePauseChain, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/NodePauseChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ObservedTxIn(ctx context.Context, in *MsgObservedTxIn, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/ObservedTxIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ObservedTxOut(ctx context.Context, in *MsgObservedTxOut, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/ObservedTxOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ObservedTxQuorum(ctx context.Context, in *MsgObservedTxQuorum, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/ObservedTxQuorum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Send(ctx context.Context, in *MsgSend, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetIPAddress(ctx context.Context, in *MsgSetIPAddress, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/SetIPAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetNodeKeys(ctx context.Context, in *MsgSetNodeKeys, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/SetNodeKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Solvency(ctx context.Context, in *MsgSolvency, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/Solvency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SolvencyQuorum(ctx context.Context, in *MsgSolvencyQuorum, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/SolvencyQuorum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TssKeysignFail(ctx context.Context, in *MsgTssKeysignFail, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/TssKeysignFail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) KeygenVault(ctx context.Context, in *MsgKeygenVault, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/KeygenVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetVersion(ctx context.Context, in *MsgSetVersion, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/SetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ProposeUpgrade(ctx context.Context, in *MsgProposeUpgrade, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/ProposeUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApproveUpgrade(ctx context.Context, in *MsgApproveUpgrade, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/ApproveUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectUpgrade(ctx context.Context, in *MsgRejectUpgrade, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/RejectUpgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PriceFeedQuorumBatch(ctx context.Context, in *MsgPriceFeedQuorumBatch, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/PriceFeedQuorumBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DepositRequestPow(ctx context.Context, in *MsgDepositRequestPow, opts ...grpc.CallOption) (*MsgDepositRequestPowResponse, error) {
	out := new(MsgDepositRequestPowResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/DepositRequestPow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ShielderShield(ctx context.Context, in *MsgShielderShield, opts ...grpc.CallOption) (*MsgShielderShieldResponse, error) {
	out := new(MsgShielderShieldResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/ShielderShield", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ShielderRedeem(ctx context.Context, in *MsgShielderRedeem, opts ...grpc.CallOption) (*MsgShielderRedeemResponse, error) {
	out := new(MsgShielderRedeemResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/ShielderRedeem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ShielderShieldFees(ctx context.Context, in *MsgShielderShieldFees, opts ...grpc.CallOption) (*MsgShielderShieldFeesResponse, error) {
	out := new(MsgShielderShieldFeesResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/ShielderShieldFees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) NodeSlotAuctionCreate(ctx context.Context, in *MsgNodeSlotAuctionCreate, opts ...grpc.CallOption) (*MsgNodeSlotAuctionCreateResponse, error) {
	out := new(MsgNodeSlotAuctionCreateResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/NodeSlotAuctionCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) NodeSlotAuctionBidPow(ctx context.Context, in *MsgNodeSlotAuctionBidPow, opts ...grpc.CallOption) (*MsgDepositRequestPowResponse, error) {
	out := new(MsgDepositRequestPowResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/NodeSlotAuctionBidPow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) NodeSlotAuctionSelectBid(ctx context.Context, in *MsgNodeSlotAuctionSelectBid, opts ...grpc.CallOption) (*MsgEmpty, error) {
	out := new(MsgEmpty)
	err := c.cc.Invoke(ctx, "/types.Msg/NodeSlotAuctionSelectBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) NodeSlotAuctionShield(ctx context.Context, in *MsgNodeSlotAuctionShield, opts ...grpc.CallOption) (*MsgShielderShieldResponse, error) {
	out := new(MsgShielderShieldResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/NodeSlotAuctionShield", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Deposit(context.Context, *MsgDeposit) (*MsgEmpty, error)
	ErrataTx(context.Context, *MsgErrataTx) (*MsgEmpty, error)
	ErrataTxQuorum(context.Context, *MsgErrataTxQuorum) (*MsgEmpty, error)
	Config(context.Context, *MsgConfig) (*MsgEmpty, error)
	NetworkFee(context.Context, *MsgNetworkFee) (*MsgEmpty, error)
	NetworkFeeQuorum(context.Context, *MsgNetworkFeeQuorum) (*MsgEmpty, error)
	NodePauseChain(context.Context, *MsgNodePauseChain) (*MsgEmpty, error)
	ObservedTxIn(context.Context, *MsgObservedTxIn) (*MsgEmpty, error)
	ObservedTxOut(context.Context, *MsgObservedTxOut) (*MsgEmpty, error)
	ObservedTxQuorum(context.Context, *MsgObservedTxQuorum) (*MsgEmpty, error)
	Send(context.Context, *MsgSend) (*MsgEmpty, error)
	SetIPAddress(context.Context, *MsgSetIPAddress) (*MsgEmpty, error)
	SetNodeKeys(context.Context, *MsgSetNodeKeys) (*MsgEmpty, error)
	Solvency(context.Context, *MsgSolvency) (*MsgEmpty, error)
	SolvencyQuorum(context.Context, *MsgSolvencyQuorum) (*MsgEmpty, error)
	TssKeysignFail(context.Context, *MsgTssKeysignFail) (*MsgEmpty, error)
	KeygenVault(context.Context, *MsgKeygenVault) (*MsgEmpty, error)
	SetVersion(context.Context, *MsgSetVersion) (*MsgEmpty, error)
	ProposeUpgrade(context.Context, *MsgProposeUpgrade) (*MsgEmpty, error)
	ApproveUpgrade(context.Context, *MsgApproveUpgrade) (*MsgEmpty, error)
	RejectUpgrade(context.Context, *MsgRejectUpgrade) (*MsgEmpty, error)
	PriceFeedQuorumBatch(context.Context, *MsgPriceFeedQuorumBatch) (*MsgEmpty, error)
	DepositRequestPow(context.Context, *MsgDepositRequestPow) (*MsgDepositRequestPowResponse, error)
	ShielderShield(context.Context, *MsgShielderShield) (*MsgShielderShieldResponse, error)
	ShielderRedeem(context.Context, *MsgShielderRedeem) (*MsgShielderRedeemResponse, error)
	ShielderShieldFees(context.Context, *MsgShielderShieldFees) (*MsgShielderShieldFeesResponse, error)
	NodeSlotAuctionCreate(context.Context, *MsgNodeSlotAuctionCreate) (*MsgNodeSlotAuctionCreateResponse, error)
	NodeSlotAuctionBidPow(context.Context, *MsgNodeSlotAuctionBidPow) (*MsgDepositRequestPowResponse, error)
	NodeSlotAuctionSelectBid(context.Context, *MsgNodeSlotAuctionSelectBid) (*MsgEmpty, error)
	NodeSlotAuctionShield(context.Context, *MsgNodeSlotAuctionShield) (*MsgShielderShieldResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Deposit(ctx context.Context, req *MsgDeposit) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (*UnimplementedMsgServer) ErrataTx(ctx context.Context, req *MsgErrataTx) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrataTx not implemented")
}
func (*UnimplementedMsgServer) ErrataTxQuorum(ctx context.Context, req *MsgErrataTxQuorum) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrataTxQuorum not implemented")
}
func (*UnimplementedMsgServer) Config(ctx context.Context, req *MsgConfig) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (*UnimplementedMsgServer) NetworkFee(ctx context.Context, req *MsgNetworkFee) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkFee not implemented")
}
func (*UnimplementedMsgServer) NetworkFeeQuorum(ctx context.Context, req *MsgNetworkFeeQuorum) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkFeeQuorum not implemented")
}
func (*UnimplementedMsgServer) NodePauseChain(ctx context.Context, req *MsgNodePauseChain) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodePauseChain not implemented")
}
func (*UnimplementedMsgServer) ObservedTxIn(ctx context.Context, req *MsgObservedTxIn) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObservedTxIn not implemented")
}
func (*UnimplementedMsgServer) ObservedTxOut(ctx context.Context, req *MsgObservedTxOut) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObservedTxOut not implemented")
}
func (*UnimplementedMsgServer) ObservedTxQuorum(ctx context.Context, req *MsgObservedTxQuorum) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObservedTxQuorum not implemented")
}
func (*UnimplementedMsgServer) Send(ctx context.Context, req *MsgSend) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedMsgServer) SetIPAddress(ctx context.Context, req *MsgSetIPAddress) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIPAddress not implemented")
}
func (*UnimplementedMsgServer) SetNodeKeys(ctx context.Context, req *MsgSetNodeKeys) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNodeKeys not implemented")
}
func (*UnimplementedMsgServer) Solvency(ctx context.Context, req *MsgSolvency) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solvency not implemented")
}
func (*UnimplementedMsgServer) SolvencyQuorum(ctx context.Context, req *MsgSolvencyQuorum) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolvencyQuorum not implemented")
}
func (*UnimplementedMsgServer) TssKeysignFail(ctx context.Context, req *MsgTssKeysignFail) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TssKeysignFail not implemented")
}
func (*UnimplementedMsgServer) KeygenVault(ctx context.Context, req *MsgKeygenVault) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeygenVault not implemented")
}
func (*UnimplementedMsgServer) SetVersion(ctx context.Context, req *MsgSetVersion) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVersion not implemented")
}
func (*UnimplementedMsgServer) ProposeUpgrade(ctx context.Context, req *MsgProposeUpgrade) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeUpgrade not implemented")
}
func (*UnimplementedMsgServer) ApproveUpgrade(ctx context.Context, req *MsgApproveUpgrade) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveUpgrade not implemented")
}
func (*UnimplementedMsgServer) RejectUpgrade(ctx context.Context, req *MsgRejectUpgrade) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectUpgrade not implemented")
}
func (*UnimplementedMsgServer) PriceFeedQuorumBatch(ctx context.Context, req *MsgPriceFeedQuorumBatch) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PriceFeedQuorumBatch not implemented")
}
func (*UnimplementedMsgServer) DepositRequestPow(ctx context.Context, req *MsgDepositRequestPow) (*MsgDepositRequestPowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositRequestPow not implemented")
}
func (*UnimplementedMsgServer) ShielderShield(ctx context.Context, req *MsgShielderShield) (*MsgShielderShieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShielderShield not implemented")
}
func (*UnimplementedMsgServer) ShielderRedeem(ctx context.Context, req *MsgShielderRedeem) (*MsgShielderRedeemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShielderRedeem not implemented")
}
func (*UnimplementedMsgServer) ShielderShieldFees(ctx context.Context, req *MsgShielderShieldFees) (*MsgShielderShieldFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShielderShieldFees not implemented")
}
func (*UnimplementedMsgServer) NodeSlotAuctionCreate(ctx context.Context, req *MsgNodeSlotAuctionCreate) (*MsgNodeSlotAuctionCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeSlotAuctionCreate not implemented")
}
func (*UnimplementedMsgServer) NodeSlotAuctionBidPow(ctx context.Context, req *MsgNodeSlotAuctionBidPow) (*MsgDepositRequestPowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeSlotAuctionBidPow not implemented")
}
func (*UnimplementedMsgServer) NodeSlotAuctionSelectBid(ctx context.Context, req *MsgNodeSlotAuctionSelectBid) (*MsgEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeSlotAuctionSelectBid not implemented")
}
func (*UnimplementedMsgServer) NodeSlotAuctionShield(ctx context.Context, req *MsgNodeSlotAuctionShield) (*MsgShielderShieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeSlotAuctionShield not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Deposit(ctx, req.(*MsgDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ErrataTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgErrataTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ErrataTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ErrataTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ErrataTx(ctx, req.(*MsgErrataTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ErrataTxQuorum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgErrataTxQuorum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ErrataTxQuorum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ErrataTxQuorum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ErrataTxQuorum(ctx, req.(*MsgErrataTxQuorum))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Config(ctx, req.(*MsgConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_NetworkFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNetworkFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).NetworkFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/NetworkFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).NetworkFee(ctx, req.(*MsgNetworkFee))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_NetworkFeeQuorum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNetworkFeeQuorum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).NetworkFeeQuorum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/NetworkFeeQuorum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).NetworkFeeQuorum(ctx, req.(*MsgNetworkFeeQuorum))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_NodePauseChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNodePauseChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).NodePauseChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/NodePauseChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).NodePauseChain(ctx, req.(*MsgNodePauseChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ObservedTxIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgObservedTxIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ObservedTxIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ObservedTxIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ObservedTxIn(ctx, req.(*MsgObservedTxIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ObservedTxOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgObservedTxOut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ObservedTxOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ObservedTxOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ObservedTxOut(ctx, req.(*MsgObservedTxOut))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ObservedTxQuorum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgObservedTxQuorum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ObservedTxQuorum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ObservedTxQuorum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ObservedTxQuorum(ctx, req.(*MsgObservedTxQuorum))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Send(ctx, req.(*MsgSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetIPAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetIPAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetIPAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/SetIPAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetIPAddress(ctx, req.(*MsgSetIPAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetNodeKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetNodeKeys)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetNodeKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/SetNodeKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetNodeKeys(ctx, req.(*MsgSetNodeKeys))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Solvency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSolvency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Solvency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/Solvency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Solvency(ctx, req.(*MsgSolvency))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SolvencyQuorum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSolvencyQuorum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SolvencyQuorum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/SolvencyQuorum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SolvencyQuorum(ctx, req.(*MsgSolvencyQuorum))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TssKeysignFail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTssKeysignFail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TssKeysignFail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/TssKeysignFail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TssKeysignFail(ctx, req.(*MsgTssKeysignFail))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_KeygenVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgKeygenVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).KeygenVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/KeygenVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).KeygenVault(ctx, req.(*MsgKeygenVault))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/SetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetVersion(ctx, req.(*MsgSetVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ProposeUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProposeUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProposeUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ProposeUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProposeUpgrade(ctx, req.(*MsgProposeUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApproveUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ApproveUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveUpgrade(ctx, req.(*MsgApproveUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/RejectUpgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectUpgrade(ctx, req.(*MsgRejectUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PriceFeedQuorumBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPriceFeedQuorumBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PriceFeedQuorumBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/PriceFeedQuorumBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PriceFeedQuorumBatch(ctx, req.(*MsgPriceFeedQuorumBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DepositRequestPow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDepositRequestPow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DepositRequestPow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/DepositRequestPow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DepositRequestPow(ctx, req.(*MsgDepositRequestPow))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ShielderShield_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShielderShield)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ShielderShield(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ShielderShield",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ShielderShield(ctx, req.(*MsgShielderShield))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ShielderRedeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShielderRedeem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ShielderRedeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ShielderRedeem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ShielderRedeem(ctx, req.(*MsgShielderRedeem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ShielderShieldFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShielderShieldFees)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ShielderShieldFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/ShielderShieldFees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ShielderShieldFees(ctx, req.(*MsgShielderShieldFees))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_NodeSlotAuctionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNodeSlotAuctionCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).NodeSlotAuctionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/NodeSlotAuctionCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).NodeSlotAuctionCreate(ctx, req.(*MsgNodeSlotAuctionCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_NodeSlotAuctionBidPow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNodeSlotAuctionBidPow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).NodeSlotAuctionBidPow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/NodeSlotAuctionBidPow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).NodeSlotAuctionBidPow(ctx, req.(*MsgNodeSlotAuctionBidPow))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_NodeSlotAuctionSelectBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNodeSlotAuctionSelectBid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).NodeSlotAuctionSelectBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/NodeSlotAuctionSelectBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).NodeSlotAuctionSelectBid(ctx, req.(*MsgNodeSlotAuctionSelectBid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_NodeSlotAuctionShield_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNodeSlotAuctionShield)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).NodeSlotAuctionShield(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/NodeSlotAuctionShield",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).NodeSlotAuctionShield(ctx, req.(*MsgNodeSlotAuctionShield))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deposit",
			Handler:    _Msg_Deposit_Handler,
		},
		{
			MethodName: "ErrataTx",
			Handler:    _Msg_ErrataTx_Handler,
		},
		{
			MethodName: "ErrataTxQuorum",
			Handler:    _Msg_ErrataTxQuorum_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _Msg_Config_Handler,
		},
		{
			MethodName: "NetworkFee",
			Handler:    _Msg_NetworkFee_Handler,
		},
		{
			MethodName: "NetworkFeeQuorum",
			Handler:    _Msg_NetworkFeeQuorum_Handler,
		},
		{
			MethodName: "NodePauseChain",
			Handler:    _Msg_NodePauseChain_Handler,
		},
		{
			MethodName: "ObservedTxIn",
			Handler:    _Msg_ObservedTxIn_Handler,
		},
		{
			MethodName: "ObservedTxOut",
			Handler:    _Msg_ObservedTxOut_Handler,
		},
		{
			MethodName: "ObservedTxQuorum",
			Handler:    _Msg_ObservedTxQuorum_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Msg_Send_Handler,
		},
		{
			MethodName: "SetIPAddress",
			Handler:    _Msg_SetIPAddress_Handler,
		},
		{
			MethodName: "SetNodeKeys",
			Handler:    _Msg_SetNodeKeys_Handler,
		},
		{
			MethodName: "Solvency",
			Handler:    _Msg_Solvency_Handler,
		},
		{
			MethodName: "SolvencyQuorum",
			Handler:    _Msg_SolvencyQuorum_Handler,
		},
		{
			MethodName: "TssKeysignFail",
			Handler:    _Msg_TssKeysignFail_Handler,
		},
		{
			MethodName: "KeygenVault",
			Handler:    _Msg_KeygenVault_Handler,
		},
		{
			MethodName: "SetVersion",
			Handler:    _Msg_SetVersion_Handler,
		},
		{
			MethodName: "ProposeUpgrade",
			Handler:    _Msg_ProposeUpgrade_Handler,
		},
		{
			MethodName: "ApproveUpgrade",
			Handler:    _Msg_ApproveUpgrade_Handler,
		},
		{
			MethodName: "RejectUpgrade",
			Handler:    _Msg_RejectUpgrade_Handler,
		},
		{
			MethodName: "PriceFeedQuorumBatch",
			Handler:    _Msg_PriceFeedQuorumBatch_Handler,
		},
		{
			MethodName: "DepositRequestPow",
			Handler:    _Msg_DepositRequestPow_Handler,
		},
		{
			MethodName: "ShielderShield",
			Handler:    _Msg_ShielderShield_Handler,
		},
		{
			MethodName: "ShielderRedeem",
			Handler:    _Msg_ShielderRedeem_Handler,
		},
		{
			MethodName: "ShielderShieldFees",
			Handler:    _Msg_ShielderShieldFees_Handler,
		},
		{
			MethodName: "NodeSlotAuctionCreate",
			Handler:    _Msg_NodeSlotAuctionCreate_Handler,
		},
		{
			MethodName: "NodeSlotAuctionBidPow",
			Handler:    _Msg_NodeSlotAuctionBidPow_Handler,
		},
		{
			MethodName: "NodeSlotAuctionSelectBid",
			Handler:    _Msg_NodeSlotAuctionSelectBid_Handler,
		},
		{
			MethodName: "NodeSlotAuctionShield",
			Handler:    _Msg_NodeSlotAuctionShield_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/tx.proto",
}

func (m *MsgEmpty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEmpty) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEmpty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgEmpty) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgEmpty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEmpty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEmpty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
