syntax = "proto3";
package thornado;

option go_package = "github.com/thornadocash/go-thornado/x/thornado";

import "types/type_chain_contract.proto";
import "types/type_network_fee.proto";
import "types/type_network.proto";
import "types/type_vault.proto";
import "types/type_tx_out.proto";
import "types/type_mimir.proto";
import "types/type_node_account.proto";
import "types/type_observed_tx.proto";
import "gogoproto/gogo.proto";

message lastChainHeight {
  string chain = 1;
  int64 height = 2;
}

message mimir {
  string key = 1;
  int64 value = 2;
}

message GenesisState {
  reserved 1, 2;
  repeated types.ObservedTxVoter observed_tx_in_voters = 3 [
    (gogoproto.castrepeated) =
        "github.com/thornadocash/go-thornado/x/thornado/types.ObservedTxVoters",
    (gogoproto.nullable) = false
  ];
  repeated types.ObservedTxVoter observed_tx_out_voters = 4 [
    (gogoproto.castrepeated) =
        "github.com/thornadocash/go-thornado/x/thornado/types.ObservedTxVoters",
    (gogoproto.nullable) = false
  ];
  repeated types.TxOut tx_outs = 5 [ (gogoproto.nullable) = false ];
  repeated types.NodeAccount node_accounts = 6 [
    (gogoproto.castrepeated) =
        "github.com/thornadocash/go-thornado/x/thornado/types.NodeAccounts",
    (gogoproto.nullable) = false
  ];
  repeated types.Vault vaults = 7 [
    (gogoproto.castrepeated) =
        "github.com/thornadocash/go-thornado/x/thornado/types.Vaults",
    (gogoproto.nullable) = false
  ];
  uint64 reserve = 8;
  reserved 9;
  int64 last_signed_height = 10;
  repeated lastChainHeight last_chain_heights = 11
      [ (gogoproto.nullable) = false ];
  reserved 12;
  types.Network network = 13 [ (gogoproto.nullable) = false ];
  reserved 14, 15, 16, 17, 18;
  reserved 19;
  repeated types.NetworkFee network_fees = 20 [ (gogoproto.nullable) = false ];
  reserved 21;
  repeated types.ChainContract chain_contracts = 22
      [ (gogoproto.nullable) = false ];
  reserved 23;
  repeated mimir mimirs = 24 [ (gogoproto.nullable) = false ];
  // store_version is deprecated in v3.0.0
  int64 store_version = 25 [ deprecated = true ];
  reserved 26, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37;
  repeated types.NodeMimir nodeMimirs = 38 [ (gogoproto.nullable) = false ];
  reserved 39, 41, 42, 43, 45;
}
