syntax = "proto3";
package types;

option go_package = "github.com/thornadocash/go-thornado/x/thorchain/types";
option (gogoproto.goproto_stringer_all) = false;
option (gogoproto.stringer_all) = false;
option (gogoproto.goproto_getters_all) = false;

import "gogoproto/gogo.proto";
import "common/common.proto";

message SolvencyVoter {
  string id = 1
      [ (gogoproto.casttype) = "github.com/thornadocash/go-thornado/common.TxID" ];
  string chain = 2 [ (gogoproto.casttype) =
                         "github.com/thornadocash/go-thornado/common.Chain" ];
  string pub_key = 3 [ (gogoproto.casttype) =
                           "github.com/thornadocash/go-thornado/common.PubKey" ];
  repeated common.Coin coins = 4 [
    (gogoproto.castrepeated) = "github.com/thornadocash/go-thornado/common.Coins",
    (gogoproto.nullable) = false
  ];
  int64 height = 5;
  int64 consensus_block_height = 6;
  repeated string signers = 7;
}
