ARG DOCKER_MIRROR=
FROM ${DOCKER_MIRROR}golang:1.24.6

# hadolint ignore=DL3008,DL4006
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    curl git jq make protobuf-compiler xz-utils sudo python3-pip \
    && rm -rf /var/cache/apt/lists

ENV GOBIN=/go/bin
ENV GOPATH=/go
ENV GOOS=linux

RUN mkdir /regtest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG COMMIT=unknown

RUN --mount=type=cache,target=/root/.cache/go-build make _build-test-regression