services:
  thornado-1:
    build:
      context: ./mock-service
      dockerfile: Dockerfile
    environment:
      MOCK_SERVICE_NAME: thornado-1
      MOCK_PORTS: "26656,26657,1317,9090"

  thornado-2:
    build:
      context: ./mock-service
      dockerfile: Dockerfile
    environment:
      MOCK_SERVICE_NAME: thornado-2
      MOCK_PORTS: "26656,26657,1317,9090"

  thornado-3:
    build:
      context: ./mock-service
      dockerfile: Dockerfile
    environment:
      MOCK_SERVICE_NAME: thornado-3
      MOCK_PORTS: "26656,26657,1317,9090"

  bifrost-1:
    build:
      context: ./mock-service
      dockerfile: Dockerfile
    environment:
      MOCK_SERVICE_NAME: bifrost-1
      MOCK_PORTS: "6040"

  bifrost-2:
    build:
      context: ./mock-service
      dockerfile: Dockerfile
    environment:
      MOCK_SERVICE_NAME: bifrost-2
      MOCK_PORTS: "6040"

  bifrost-3:
    build:
      context: ./mock-service
      dockerfile: Dockerfile
    environment:
      MOCK_SERVICE_NAME: bifrost-3
      MOCK_PORTS: "6040"
