// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/msg_manage_thorname.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	common "github.com/thornadocash/go-thornado/common"
	github_com_thornadocash_go_thornado_common "github.com/thornadocash/go-thornado/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgManageTHORName struct {
	Name                                string                                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chain                               github_com_thornadocash_go_thornado_common.Chain   `protobuf:"bytes,2,opt,name=chain,proto3,casttype=github.com/thornadocash/go-thornado/common.Chain" json:"chain,omitempty"`
	Address                             github_com_thornadocash_go_thornado_common.Address `protobuf:"bytes,3,opt,name=address,proto3,casttype=github.com/thornadocash/go-thornado/common.Address" json:"address,omitempty"`
	Coin                                common.Coin                                        `protobuf:"bytes,4,opt,name=coin,proto3" json:"coin"`
	ExpireBlockHeight                   int64                                              `protobuf:"varint,5,opt,name=expire_block_height,json=expireBlockHeight,proto3" json:"expire_block_height,omitempty"`
	PreferredAsset                      github_com_thornadocash_go_thornado_common.Asset   `protobuf:"bytes,6,opt,name=preferred_asset,json=preferredAsset,proto3,customtype=github.com/thornadocash/go-thornado/common.Asset" json:"preferred_asset"`
	Owner                               github_com_cosmos_cosmos_sdk_types.AccAddress      `protobuf:"bytes,7,opt,name=owner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"owner,omitempty"`
	Signer                              github_com_cosmos_cosmos_sdk_types.AccAddress      `protobuf:"bytes,8,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	PreferredAssetOutboundFeeMultiplier int64                                              `protobuf:"varint,9,opt,name=preferred_asset_outbound_fee_multiplier,json=preferredAssetOutboundFeeMultiplier,proto3" json:"preferred_asset_outbound_fee_multiplier,omitempty"`
}

func (m *MsgManageTHORName) Reset()         { *m = MsgManageTHORName{} }
func (m *MsgManageTHORName) String() string { return proto.CompactTextString(m) }
func (*MsgManageTHORName) ProtoMessage()    {}
func (*MsgManageTHORName) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf2584b8e9fdfb5c, []int{0}
}
func (m *MsgManageTHORName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgManageTHORName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgManageTHORName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgManageTHORName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgManageTHORName.Merge(m, src)
}
func (m *MsgManageTHORName) XXX_Size() int {
	return m.Size()
}
func (m *MsgManageTHORName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgManageTHORName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgManageTHORName proto.InternalMessageInfo

func (m *MsgManageTHORName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgManageTHORName) GetChain() github_com_thornadocash_go_thornado_common.Chain {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *MsgManageTHORName) GetAddress() github_com_thornadocash_go_thornado_common.Address {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgManageTHORName) GetCoin() common.Coin {
	if m != nil {
		return m.Coin
	}
	return common.Coin{}
}

func (m *MsgManageTHORName) GetExpireBlockHeight() int64 {
	if m != nil {
		return m.ExpireBlockHeight
	}
	return 0
}

func (m *MsgManageTHORName) GetOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *MsgManageTHORName) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *MsgManageTHORName) GetPreferredAssetOutboundFeeMultiplier() int64 {
	if m != nil {
		return m.PreferredAssetOutboundFeeMultiplier
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgManageTHORName)(nil), "types.MsgManageTHORName")
}

func init() { proto.RegisterFile("types/msg_manage_thorname.proto", fileDescriptor_bf2584b8e9fdfb5c) }

var fileDescriptor_bf2584b8e9fdfb5c = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x63, 0xea, 0xa4, 0x74, 0x29, 0xa0, 0x6e, 0x39, 0x58, 0x3d, 0xd8, 0x11, 0x48, 0x90,
	0x4b, 0x6c, 0x28, 0x7f, 0xc4, 0x35, 0x46, 0x82, 0x82, 0x14, 0x82, 0xac, 0x9e, 0xb8, 0x58, 0xce,
	0x7a, 0xba, 0x5e, 0x35, 0xeb, 0xb1, 0x76, 0x1d, 0x51, 0xde, 0x82, 0xc7, 0xea, 0xb1, 0x47, 0xc4,
	0x21, 0x42, 0xc9, 0x53, 0x90, 0x13, 0xf2, 0x6e, 0x5c, 0x01, 0x27, 0xd2, 0xd3, 0xce, 0xce, 0x37,
	0xf3, 0x9b, 0xf1, 0xe7, 0x25, 0x41, 0xfd, 0xb5, 0x02, 0x1d, 0x49, 0xcd, 0x53, 0x99, 0x95, 0x19,
	0x87, 0xb4, 0x2e, 0x50, 0x95, 0x99, 0x84, 0xb0, 0x52, 0x58, 0x23, 0xed, 0x9a, 0x82, 0xa3, 0x43,
	0x86, 0x52, 0x62, 0x19, 0xd9, 0xc3, 0x6a, 0x47, 0x0f, 0x38, 0x72, 0x34, 0x61, 0xd4, 0x44, 0x36,
	0xfb, 0xf0, 0x97, 0x4b, 0x0e, 0xc6, 0x9a, 0x8f, 0x0d, 0xee, 0xf4, 0x64, 0x92, 0x7c, 0xcc, 0x24,
	0x50, 0x4a, 0xdc, 0x86, 0xea, 0x39, 0x7d, 0x67, 0xb0, 0x97, 0x98, 0x98, 0x7e, 0x20, 0x5d, 0x56,
	0x64, 0xa2, 0xf4, 0x6e, 0x35, 0xc9, 0xf8, 0xc5, 0x7a, 0x11, 0x3c, 0xe5, 0xa2, 0x2e, 0xe6, 0xd3,
	0x90, 0xa1, 0x8c, 0xec, 0x26, 0x39, 0xb2, 0x4c, 0x17, 0x11, 0xc7, 0x61, 0x7b, 0x6f, 0x97, 0x78,
	0xd3, 0xf4, 0x26, 0x16, 0x41, 0x3f, 0x91, 0xdd, 0x2c, 0xcf, 0x15, 0x68, 0xed, 0xed, 0x18, 0xda,
	0xab, 0xf5, 0x22, 0x38, 0xde, 0x82, 0x36, 0xb2, 0xdd, 0x49, 0x8b, 0xa1, 0x8f, 0x89, 0xcb, 0x50,
	0x94, 0x9e, 0xdb, 0x77, 0x06, 0x77, 0x8e, 0xf7, 0xc3, 0x76, 0x2a, 0x8a, 0x32, 0x76, 0x2f, 0x17,
	0x41, 0x27, 0x31, 0x3a, 0x0d, 0xc9, 0x21, 0x5c, 0x54, 0x42, 0x41, 0x3a, 0x9d, 0x21, 0x3b, 0x4f,
	0x0b, 0x10, 0xbc, 0xa8, 0xbd, 0x6e, 0xdf, 0x19, 0xec, 0x24, 0x07, 0x56, 0x8a, 0x1b, 0xe5, 0xc4,
	0x08, 0xb4, 0x22, 0xf7, 0x2b, 0x05, 0x67, 0xa0, 0x14, 0xe4, 0x69, 0xa6, 0x35, 0xd4, 0x5e, 0xcf,
	0x8c, 0xb8, 0xdb, 0x8e, 0x18, 0x35, 0xc9, 0xf8, 0x75, 0x33, 0xe3, 0xc7, 0x76, 0x96, 0x98, 0xce,
	0xe4, 0xde, 0x35, 0xdf, 0xdc, 0xe9, 0x3b, 0xd2, 0xc5, 0x2f, 0x25, 0x28, 0x6f, 0xb7, 0xef, 0x0c,
	0xf6, 0xe3, 0x67, 0xeb, 0x45, 0x30, 0xfc, 0x03, 0xca, 0x50, 0x4b, 0xd4, 0x9b, 0x63, 0xa8, 0xf3,
	0xf3, 0xc8, 0xfc, 0xf3, 0x70, 0xc4, 0x58, 0x6b, 0x8a, 0xed, 0xa7, 0xef, 0x49, 0x4f, 0x0b, 0xde,
	0x90, 0x6e, 0xdf, 0x94, 0xb4, 0x01, 0xd0, 0x53, 0xf2, 0xe4, 0x1f, 0x17, 0x52, 0x9c, 0xd7, 0x53,
	0x9c, 0x97, 0x79, 0x7a, 0x06, 0x90, 0xca, 0xf9, 0xac, 0x16, 0xd5, 0x4c, 0x80, 0xf2, 0xf6, 0x8c,
	0x93, 0x8f, 0xfe, 0xfe, 0xa8, 0xc9, 0xa6, 0xf8, 0x2d, 0xc0, 0xf8, 0xba, 0x34, 0x9e, 0x5c, 0x2e,
	0x7d, 0xe7, 0x6a, 0xe9, 0x3b, 0x3f, 0x97, 0xbe, 0xf3, 0x6d, 0xe5, 0x77, 0xae, 0x56, 0x7e, 0xe7,
	0xfb, 0xca, 0xef, 0x7c, 0x7e, 0xf9, 0x3f, 0x2e, 0x5e, 0x18, 0xc9, 0x3c, 0x28, 0xbb, 0xf9, 0xb4,
	0x67, 0xde, 0xf4, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x40, 0x4d, 0x77, 0x28, 0x03,
	0x00, 0x00,
}

func (m *MsgManageTHORName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgManageTHORName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgManageTHORName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PreferredAssetOutboundFeeMultiplier != 0 {
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(m.PreferredAssetOutboundFeeMultiplier))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.PreferredAsset.Size()
		i -= size
		if _, err := m.PreferredAsset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.ExpireBlockHeight != 0 {
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(m.ExpireBlockHeight))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMsgManageThorname(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgManageThorname(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgManageThorname(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgManageTHORName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMsgManageThorname(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovMsgManageThorname(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMsgManageThorname(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovMsgManageThorname(uint64(l))
	if m.ExpireBlockHeight != 0 {
		n += 1 + sovMsgManageThorname(uint64(m.ExpireBlockHeight))
	}
	l = m.PreferredAsset.Size()
	n += 1 + l + sovMsgManageThorname(uint64(l))
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovMsgManageThorname(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgManageThorname(uint64(l))
	}
	if m.PreferredAssetOutboundFeeMultiplier != 0 {
		n += 1 + sovMsgManageThorname(uint64(m.PreferredAssetOutboundFeeMultiplier))
	}
	return n
}

func sovMsgManageThorname(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgManageThorname(x uint64) (n int) {
	return sovMsgManageThorname(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgManageTHORName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgManageThorname
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgManageTHORName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgManageTHORName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = github_com_thornadocash_go_thornado_common.Chain(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = github_com_thornadocash_go_thornado_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireBlockHeight", wireType)
			}
			m.ExpireBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpireBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferredAsset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PreferredAsset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferredAssetOutboundFeeMultiplier", wireType)
			}
			m.PreferredAssetOutboundFeeMultiplier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreferredAssetOutboundFeeMultiplier |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgManageThorname(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgManageThorname
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgManageThorname(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgManageThorname
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgManageThorname
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgManageThorname
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgManageThorname
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgManageThorname
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgManageThorname        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgManageThorname          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgManageThorname = fmt.Errorf("proto: unexpected end of group")
)
